### ISSUE TITLE
Cannot see client connections details

### ISSUE THREAD

**Issue by dryshliak** [furlongm/openvpn-monitor#1]
I cannot see client connection only count of connection and bytes in and bytes out:
![2015-10-06_12-02](https://cloud.githubusercontent.com/assets/6420481/10348249/a63dea92-6d40-11e5-997c-0b3c5715de63.jpg)

When i'm running script in debug mode i see information that is collected by the script about client connections but generated empty html file.

Thanks!
Log:
root@raspberrypi:/var/www/openvpn# ./openvpn-monitor.py -d
=== begin section
{'maps': 'False', 'site': ''}
=== end section
=== begin section
{'host': '192.168.1.1', 'port': '1150', 'name': 'VPN'}
=== end section
=== begin raw data
1444084336,CONNECTED,SUCCESS,192.168.2.1,
END

=== end raw data
=== begin split line
['1444084336', 'CONNECTED', 'SUCCESS', '192.168.2.1', '']
=== end split line
=== begin split line
['END']
=== end split line
=== begin raw data
SUCCESS: nclients=1,bytesin=7430387,bytesout=5210173

=== end raw data
=== begin split line
['nclients=1', 'bytesin=7430387', 'bytesout=5210173\r\n']
=== end split line
=== begin raw data
TITLE,OpenVPN 2.3.6 arm-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [MH] [IPv6] built on Jun 10 2015
TIME,Wed Oct  7 22:04:52 2015,1444244692
HEADER,CLIENT_LIST,Common Name,Real Address,Virtual Address,Bytes Received,Bytes Sent,Connected Since,Connected Since (time_t),Username
CLIENT_LIST,client,1.1.1.1:49157,192.168.2.2,637356,172249,Wed Oct  7 12:03:00 2015,1444208580,UNDEF
HEADER,ROUTING_TABLE,Virtual Address,Common Name,Real Address,Last Ref,Last Ref (time_t)
ROUTING_TABLE,192.168.2.2,client,1.1.1.1:49157,Wed Oct  7 21:34:37 2015,1444242877
GLOBAL_STATS,Max bcast/mcast queue length,0
END

=== end raw data
=== begin split line
['TITLE', 'OpenVPN 2.3.6 arm-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [MH] [IPv6] built on Jun 10 2015']
=== end split line
=== begin split line
['TIME', 'Wed Oct  7 22:04:52 2015', '1444244692']
=== end split line
=== begin split line
['HEADER', 'CLIENT_LIST', 'Common Name', 'Real Address', 'Virtual Address', 'Bytes Received', 'Bytes Sent', 'Connected Since', 'Connected Since (time_t)', 'Username']
=== end split line
=== begin split line
['CLIENT_LIST', 'client', '1.1.1.1:49157', '192.168.2.2', '637356', '172249', 'Wed Oct  7 12:03:00 2015', '1444208580', 'UNDEF']
=== end split line
=== begin split line
['HEADER', 'ROUTING_TABLE', 'Virtual Address', 'Common Name', 'Real Address', 'Last Ref', 'Last Ref (time_t)']
=== end split line
=== begin split line
['ROUTING_TABLE', '192.168.2.2', 'client', '1.1.1.1:49157', 'Wed Oct  7 21:34:37 2015', '1444242877']
=== end split line
=== begin split line
['GLOBAL_STATS', 'Max bcast/mcast queue length', '0']
=== end split line
=== begin split line
['END']
=== end split line
Content-Type: text/html

<!doctype html>
<html><head><meta charset="utf-8"><title> OpenVPN Status Monitor</title>
<meta http-equiv='refresh' content='300' />
<style type="text/css">
body { font-family: sans-serif; font-size: 12px; background-color: #FFFFFF; margin: auto; }
h1 { color: #222222; font-size: 20px; text-align: center; padding-bottom: 0; margin-bottom: 0; }
table { margin: auto; width:900px; border-collapse: collapse; }
td.left {text-align: left; color: #232355; font-weight: bold; font-size: 14px; }
td.right {text-align: right; color: #656511; font-weight: bold; font-size: 14px; }
th { background: #555555; color: white; text-align: left; padding-left: 10px;}
td { padding: 10px 10px 5px 5px; }
div { padding: 7px 4px 6px 6px; margin: 0px auto; text-align: center; }
div.footer { text-align: center; }
</style></head><body onload="initialize()">
<h1> OpenVPN Status Monitor</h1><br />
<div><table><tr><td class="left">VPN - Connection up, pingable. 1 clients, 7430387 bytes in, 5210173
 bytes out </td><td class="right">[ 192.168.2.1
tun
]</td></tr></table>
<table><tr>
<th>Username / Hostname</th>
<th>VPN IP Address</th>
<th>Remote IP Address</th>
<th>Port</th>
<th>Location</th>
<th>Recv</th>
<th>Sent</th>
<th>Connected Since</th>
<th>Last Ping</th>
<th>Time Online</th>
</tr>
</table></div><br /><br />
=== begin vpns
{'VPN1': {'stats': {'nclients': '1', 'bytesout': '5210173\r\n', 'bytesin': '7430387'}, 'name': 'VPN', 'sessions': {}, 'state': {'type': 'tun', 'identifier': '1444084336', 'connected': 'CONNECTED', 'success': 'SUCCESS', 'local_ip': '192.168.2.1'}, 'socket_connect': True, 'host': '192.168.1.1', 'port': '1150'}}
=== end vpns
<div class="footer">Page automatically reloads every 5 minutes.<br/>Last update: <b>Wed 07/10/2015 22:04:52</b></div>
</body>
</html>

**Comment by furlongm** [comment]
On first glance, it seems to be the new columns "Last Ref (time_t)" and "Connected Since (time_t)" that are causing the issue. I'll need to get an installation of the same version up and running to test.

**Comment by dryshliak** [comment]
Hello,
I have tested on OpenVPN 2.3.7 version but the are 2.3.8 and i think you can use latest version.
Thanks

**Comment by furlongm** [comment]
As a workaround, you can add `status-version 1` to your openvpn config file.
