### ISSUE TITLE
[cgid:error] [pid 9528] End of script output before headers: openvpn-monitor.py

### ISSUE THREAD

**Issue by jamestombs** [furlongm/openvpn-monitor#10]
Ubuntu 14.04
Apache 2.4
Python 2.7.6

Get a 500 HTTP error code when visiting the page from the browser.

Running `python openmonitor.py` directly from the folder outputs the full HTML.

**Comment by furlongm** [comment]
Was it set up exactly as per the README? It looks like apache doesn't get the headers or html from the script.

**Comment by jamestombs** [comment]
Yes, vhost config is:

```
<Directory /home/site-name/public_html>
Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
allow from all
AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
Require all granted
AddHandler cgi-script .py
DirectoryIndex openvpn-monitor.py
</Directory>
```

**Comment by furlongm** [comment]
Permissions for apache user on /home/site-name/public_html/* are ok?

Anything else in the apache error logs?

**Comment by jamestombs** [comment]
Ah ha, got it to work eventually. TL;DR: Permissions

Background: Vhost set up through Webmin. Script is in the root of the vhost, not a sub-folder. Folder and files are owned by the user.

The vhost has `SuexecUserGroup "#1032" "#1032"` so it should be running as the webmin user (which matches that user ID).

The main Apache has: `suexec policy violation: see suexec log for more details` but I can't seem to find it.

Checking the suexec log:

```
[2016-06-29 13:59:00]: uid: (1032/site-name) gid: (1032/site-name) cmd: openvpn-monitor.py
[2016-06-29 13:59:00]: file is writable by others: (/home/site-name/public_html/openvpn-monitor.py)
```

In the end I set 755 to folder and files and it still didn't work, so did a chmod +x to folder and python file and it's working now.

**Comment by furlongm** [comment]
Happy to hear it :)
