### ISSUE TITLE
SE Linux port 5555

### ISSUE THREAD

**Issue by perfecto25** [furlongm/openvpn-monitor#101]
Thanks for the excellent monitor, works great!

Wanted to add that maybe you want to add this to tthe README for SELinux to allow custom OpenVPN management port, 

```
sudo semanage port -a -t openvpn_port_t -p tcp 5555
```

otherwise openvpn service wont start up.

thanks.

**Comment by furlongm** [comment]
Thanks for the info. What distribution is this required on?

**Comment by furlongm** [comment]
Closing pending addition to README once we know what distro this is on.
