### ISSUE TITLE
geoip issue

### ISSUE THREAD

**Issue by ilyadavydyuk** [furlongm/openvpn-monitor#103]
if i run openvpn-monitor.py from terminal - i get geoip working (<td><img src="images/flags/ru.png" title="Kotel'niki, MOS, Russia" alt="Kotel'niki, MOS, Russia" />
Kotel'niki, MOS, Russia</td>) for example. But on web page i still get "Unknown" in location column...

i use apache2. and in error.log i get WARNING: No compatible geoip1 or geoip2 data/libraries found.

**Comment by furlongm** [comment]
Can you add the output of the debugging instructions?

**Comment by furlongm** [comment]
Closing due to no reply. Feel free to reopen.
