### ISSUE TITLE
cannot access

### ISSUE THREAD

**Issue by hardzink** [furlongm/openvpn-monitor#11]
![untitled](https://cloud.githubusercontent.com/assets/18180219/16657825/6db28cc2-4496-11e6-9645-53f07db8735c.png)

i cannot access after install

**Comment by hardzink** [comment]
do u have any video tutorial for this setup admin?

**Comment by furlongm** [comment]
Can you check your web server error logs to see what the error is?

**Comment by hardzink** [comment]
sory i;m new..
how to see log?

**Comment by hardzink** [comment]
do u have any chat sir?

**Comment by hardzink** [comment]
/var/www/html# a2enmod python cgid
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "False"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Module python already enabled
Enabling module cgid.
To activate the new configuration, you need to run:
  service apache2 restart

**Comment by hardzink** [comment]
sory my mistake.
now already done.
tq so much
