### ISSUE TITLE
Sort column default by username

### ISSUE THREAD

**Issue by jrmagots** [furlongm/openvpn-monitor#113]
Just an ideia, 
Everyone I access te page I sort by first column. It could be great if the fist column load sorted by default.

Thansks for the great work guys

**Comment by luksol** [comment]
You can do it by modifying openvpn-monitor.py

Find this line:
`output('$("table.tablesorter").tablesorter({ theme:"bootstrap", headerTemplate:"{content} {icon}", widgets:["uitheme"]});')`

And add default sdorting option to it, so it looks like that:
`output('$("table.tablesorter").tablesorter({ sortList: [[0,0]], theme:"bootstrap", headerTemplate:"{content} {icon}", widgets:["uitheme"]});')`

remember to reboot your application server so changes are reloaded

**Comment by jrmagots** [comment]
@luksol It works, thank you :)
