### ISSUE TITLE
Location in Ubuntu 16

### ISSUE THREAD

**Issue by xyboox** [furlongm/openvpn-monitor#115]
The issue: location of connected clients is always "Unknown".

So, to start with the beginning: I'm using apache to run the script. At install time, apt-get returns an error when trying to install python-geoip2: 

`E: Unable to locate package python-geoip2`

I was however able to install geoip2 lib using pip.
All the other packages were installed.

The script works in all other regards, but no location detected ( and therefore no pins on the map also ).

Q: are there any logs generated when running in apache? Checked apache logs but there's nothing ( except access log and error - but the error log has nothing related to openvpn-monitor inside ). I see in the .py script there are log messages generated but just can't find them so I can get a hint on why location is not working.

Any idea?
Thanks!

BTW: when running 

`geoiplookup -f /usr/share/GeoIP/GeoIPCity.dat 188.24.x.x` 

it returns the location data properly.

**Comment by ftoledo** [comment]
are you installed for you python2 o python3 version?

**Comment by furlongm** [comment]
Looks like that package is only available in 18.04 (bionic) and up:

https://packages.ubuntu.com/search?keywords=python-geoip2

There are instructions for running on the command line with debug options in the README. Can you post the output here?

**Comment by xyboox** [comment]
Thanks for the answer but I have upgraded meantime to bionic and is now working ok.
