### ISSUE TITLE
How to install it on CentOS 7

### ISSUE THREAD

**Issue by gnufreex** [furlongm/openvpn-monitor#12]
I am having toruble installing it as mod_python is not available on centos7. I downloaded and compiled mod_python but it turns out that it is version 3.5 and 2.7 is needed. Cant find it. Any solutions?

**Comment by EsWees** [comment]
```
yum install -y epel-release
yum update -y
yum install -y \
		httpd \
		git \
		wget \
	  	python-ipaddr \
		python-GeoIP \
		python-humanize \

git clone https://github.com/furlongm/openvpn-monitor.git /var/www/html

wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

gunzip GeoLiteCity.dat.gz

mv GeoLiteCity.dat /usr/share/GeoIP/GeoIPCity.dat
```
in httpd config:
```
<Directory "/var/www/html">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
    Options +ExecCGI
    AddHandler cgi-script .py
    DirectoryIndex openvpn-monitor.py
</Directory>

```

**Comment by puqing** [comment]
I am running this program on CentOS 6.7 with python3 and uwsgi. It seems work fine. Apache is not used. I think on CentOS 7 you can run this program in the same way.

I used pip to install the dependencies:

# yum install GeoIP-devel
# pip3 install GeoIP, bottle, humanize, uwsgi
$ uwsgi --wsgi-file openvpn-monitor.py --http :8088
