### ISSUE TITLE
More of a Question

### ISSUE THREAD

**Issue by clearclarencs** [furlongm/openvpn-monitor#122]
I appologise in advance as I dont really understand everything but im trying my best.
I have set it up and it works beutifully love the UI and the vpn profiles are showing, the only thing is it only works on Lan (192.168.0.28/openvpn-monitor/), ive tried port forwarding with different ports and tried to connect through wan (WanIp:port/openvpn-monitor/) but havent been able to.
Probably something really simple that i messed up or something but what port should i be using and forwarding?
This is to access the monitor by the way the vpn connects to the monitor fine.

Thanks in advance, James

**Comment by furlongm** [comment]
Not really an openvpn-monitor issue per se. Closing as it's out of scope. Maybe https://portforward.com/ might be helpful to you.
