### ISSUE TITLE
Help to install openvpn-monitor

### ISSUE THREAD

**Issue by PrzemekSkw** [furlongm/openvpn-monitor#127]
Hi, I try to install openvpn-monitor on my Debian 10 and every method I have errors during install. I add line `management 127.0.0.1 5555` and only effect I get is:
![Zrzut ekranu z 2020-01-12 15-34-35](https://user-images.githubusercontent.com/25219988/72220464-1fc74e80-3551-11ea-8b9b-c2395316a50f.png)
Can somebody help me and give me step by step tutorial how to install.
Regards.

Edit.
ok, I did it.

**Comment by KleKlai** [comment]
can you give step by step on how did you install it on debian 10? @PrzemekSkw

**Comment by PrzemekSkw** [comment]
@KleKlai I struggling with installation in docker (but failed so I remove docker instance). Then I install with that way:
```
# apt-get install python-virtualenv geoip-database-extra geoipupdate      # (debian/ubuntu)
mkdir /srv/openvpn-monitor
cd /srv/openvpn-monitor
virtualenv .
. bin/activate
pip install --upgrade pip
pip install openvpn-monitor gunicorn
gunicorn openvpn-monitor -b 0.0.0.0:80
```
and with that:
```
apt-get -y install git apache2 libapache2-mod-wsgi python-geoip2 python-ipaddr python-humanize python-bottle python-semantic-version geoip-database-extra geoipupdate
echo "WSGIScriptAlias /openvpn-monitor /var/www/html/openvpn-monitor/openvpn-monitor.py" > /etc/apache2/conf-available/openvpn-monitor.conf
a2enconf openvpn-monitor
systemctl restart apache2
```
That doesn't work because I don't change wright my `server.conf` file.

It start working when I add to my `/etc/openvpn/server.conf` line
`management myserverIP myserverPort`

I also install file [geoipupdate_4.1.5_linux_amd64.deb](https://github.com/maxmind/geoipupdate/releases)
I change file openvpn-monitor.conf
```
root@OpenVPN:/var/www/html/openvpn-monitor# cat openvpn-monitor.conf
[openvpn-monitor]
site=Panel
#logo=/logo.jpg
latitude=45.7059
longitude=9.5872
maps=True
geoip_data=/usr/lib/geoip
datetime_format=%d/%m/%Y %H:%M:%S

[VPN1]
host=myserverIP
port=myserver Port
name=OpenVPN
show_disconnect=False
```
and start in web browser: `http://myserverIP/openvpn-monitor`

**Comment by PrzemekSkw** [comment]
@KleKlai Hi, I install with:
```
# apt-get install python-virtualenv geoip-database-extra geoipupdate      # (debian/ubuntu)
mkdir /srv/openvpn-monitor
cd /srv/openvpn-monitor
virtualenv .
. bin/activate
pip install --upgrade pip
pip install openvpn-monitor gunicorn
gunicorn openvpn-monitor -b 0.0.0.0:80
```
and it works but don't know how to enable that to work after reboot.
Regards,
Przemek
