### ISSUE TITLE
[Centos][SELinux] Connection to 5555 port

### ISSUE THREAD

**Issue by metalrise** [furlongm/openvpn-monitor#136]
First of all, thank you for the lightweight solution for monitoring OpenVPN

After I've installed the monitor, there were same issues caused by SELinux on CentOS 7:

a) OpenVPN not starting after adding management 127.0.0.1 5555 to server.conf

This has solved by the fix recommended in issue https://github.com/furlongm/openvpn-monitor/issues/101

In CentOS 7 minimal, semanage is installed by policycoreutils-python

`yum install policycoreutils-python`
`sudo semanage port -a -t openvpn_port_t -p tcp 5555`

b) The python script cannot connect to the management interface
WARNING: socket error: [Errno 13] Permission denied from apache error_log

`setsebool -P httpd_can_network_connect=1`

httpd_can_network_connect (HTTPD Service):: Allow HTTPD scripts and modules to connect to the network

Can you update the README? and save some hours for future users from searching the web

The solutions from above were tested on CentOS 7

Another hardcore fix, can be .......... disabling SELinux

**Comment by b3hroo2** [comment]
b worked for me thanks

**Comment by PtrckM** [comment]
I think @metalrise was right it should be added to README, I already disabled SeLinux on my Centos 7 before I even see the real solution here.

**Comment by furlongm** [comment]
Happy to take a PR to add this to the README. Maybe against develop branch?

**Comment by furlongm** [comment]
Instructions updated
