### ISSUE TITLE
Adding management config to OpenVPN version 2.7

### ISSUE THREAD

**Issue by NetSnipe-20** [furlongm/openvpn-monitor#151]
Hi there,

I just fired up the monitoring on the same host as the vpn server and I can access the monitoring site(obviously it's giving me connection refused) as I have NOT added the "management 127.0.0.1 5555" entry on the vpn server as I am not so sure where to properly do this. I have tried adding it via openvpn web gui administration through additional server config directives but once I update the running AS admin console breaks and become inaccessible.

Please help

**Comment by furlongm** [comment]
I have only run this with the open source version of openvpn.

**Comment by felixmeggison** [comment]
> Hi there,
> 
> I just fired up the monitoring on the same host as the vpn server and I can access the monitoring site(obviously it's giving me connection refused) as I have NOT added the "management 127.0.0.1 5555" entry on the vpn server as I am not so sure where to properly do this. I have tried adding it via openvpn web gui administration through additional server config directives but once I update the running AS admin console breaks and become inaccessible.
> 
> Please help

try to add it using --management 127.0.0.1 5555 on etc/openvpn/server/server.conf   then restart the server

**Comment by furlongm** [comment]
Closing as it has not been tested with AS.
