### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by PPillau** [furlongm/openvpn-monitor#152]
I am getting a connfection refused error and I am don't really know why. Most probably I am configuring host and or port wrongly...
So basically I have a docker instance of openvpn running ob my ubuntu server, which is available via example.com domain with ddns. Trying to setup openvpn-monitor on the same ubuntu server.
Now does the host have to be my example.com, the ip adress of my ubuntu-server device in my local home network (192.168.XXX.XXX), 127.0.0.1 or something entirely else I am missing? In case I want to put my openvpn under vpn.example.com which also connects via ddns to my ubuntu server, do I have to put the subdomain into the host as well?

**Comment by evilhope** [comment]
Hi, I am deploying a openvpn implementation and I wanna to put the monitor xyz.mydomain.com, i try to accomplish that in many ways and I couldn't. I would like to know if exists a way to define a specific domain(I have 3 independent domains) or it's possible implement a virtualhost to this service.
btw, i run openvpn-monitor.py and works properly!
Thank you and sorry for my english

**Comment by evilhope** [comment]
Hi PPillau 
I think I have the same issue. My approach was create a virtualhost that points your subdomain.
i set   [host = 127.0.0.1  --> openvpn-monitor.conf]   and add the following line into /etc/openvpn/server.conf as furlongm explains 
management 127.0.0.1 5555
I am working upon Ubuntu 16.04 LTS 
If you need a some detail I can try to help

**Comment by furlongm** [comment]
Closing as the question is out of scope of the project.
