### ISSUE TITLE
Sort by date, incorrect sorting when clients connected by over 24 hours

### ISSUE THREAD

**Issue by simonwhill** [furlongm/openvpn-monitor#154]
Hi,
when a client has been connected for over 1 day the sorting by time online sorts incorrectly and treats the number of days as number of hours connected (see attached image).

![Capture](https://user-images.githubusercontent.com/13153804/81191102-8cf36980-8fb0-11ea-9587-872a257e2df6.PNG)

Any chance this bug can be looked at please?

Thanks

Simon

**Comment by furlongm** [comment]
Untested, but looks like the duration parser might be able to handle this:  https://mottie.github.io/tablesorter/docs/example-parsers-duration.html

**Comment by simonwhill** [comment]
Looks good, will you add this to the existing project?

Regards

Simon

**Comment by furlongm** [comment]
Can you test the above commit and see if it works as expected?

**Comment by furlongm** [comment]
@simonwhill does #169 fix the issue?

**Comment by simonwhill** [comment]
HI, Im not sure how to do that? can you give me a pointer?

Thanks

Simon

**Comment by furlongm** [comment]
You could add/remove the lines in #169 to openvpn-monitor.py

Or if if you installed from git, you could do `git pull; git checkout tablesort-durations`

**Comment by simonwhill** [comment]
yes that solves the issue, thanks 

Simon
![Capture](https://user-images.githubusercontent.com/13153804/91989092-006f7280-ed28-11ea-9a27-374b6941fd5b.PNG)

**Comment by furlongm** [comment]
Great, thanks for testing!
