### ISSUE TITLE
Client Location

### ISSUE THREAD

**Issue by DemonRok** [furlongm/openvpn-monitor#155]
In the client list I only have RFC1918, Internet RFC1918, Internet.
but if I check in the OpenVPN logs, I see the public IP of the clients.
What can I modify?
Thanks.

OpenVPN 2.4.7

**Comment by furlongm** [comment]
Can you provide some debug output?

**Comment by DemonRok** [comment]
Of course. Was there.
Now I am the only one logged in, but this morning there were 90 clients and all with the same private remote address 192.168.255.1 that however is the gateway for OpenVPN Server

Contrary to what I wrote earlier, in the openvpn logs all clients do not have public IP, so I suppose it depends on an error in my configuration

[ovpn-monitor-debug.txt](https://github.com/furlongm/openvpn-monitor/files/4617190/ovpn-monitor-debug.txt)

**Comment by DemonRok** [comment]
I confirm! It's a configuration error of my Fortigate firewall, NAT was enabled!
Sorry!
