### ISSUE TITLE
Issue with geoip-database-extra

### ISSUE THREAD

**Issue by zaduna** [furlongm/openvpn-monitor#158]
$ sudo apt-get install geoip-database-extra
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package geoip-database-extra is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**E: Package 'geoip-database-extra' has no installation candidate**

OS : Ubuntu Server 20.04 LTS

**Comment by furlongm** [comment]
Please check out the `develop` branch for Ubuntu 20.04. Still a work in progress at the moment but let me know if it works or now for you?

**Comment by furlongm** [comment]
@zaduna did the `develop` branch work for you?

**Comment by furlongm** [comment]
Closing for now due to lack of response. Feel free to reopen if the develop branch doesn't work for you.

**Comment by wagnerjsilvadrewberry** [comment]
This is still an issue....how do we get around it?
