### ISSUE TITLE
Does / Can openvpn-monitor support a management interface password?

### ISSUE THREAD

**Issue by marcovanbeek** [furlongm/openvpn-monitor#159]
As in when using management IP port **[pw-file]** in the server config.

I have two sites with two separate OpenVPN servers and it is nice to be able to centrally monitor them, but it would be even nicer to be able to password protect the management port. Although I do understand the communications are not encrypted and I probably ought to firewall the management port off to allow only the monitoring server,

**Comment by furlongm** [comment]
#51 is a PR to support a password-protected interface. Needs a little work but the main bits are there.
