### ISSUE TITLE
Change Username / Hostname from .ovpn-file to actual connected hostname

### ISSUE THREAD

**Issue by emilravn** [furlongm/openvpn-monitor#168]
Hi. This issue might not be related directly to OpenVPN Status Monitor but as of now users connected to the VPN shows up as having their username / hostname set to client, which is what the .ovpn-file is named. How do I change this to show the hostname of the connected hosts/users instead of the .ovpn file?
![Annotation 2020-07-13 135534](https://user-images.githubusercontent.com/46424499/87301829-89c8ac80-c510-11ea-9e89-3af0ae9a7c84.png)

**Comment by furlongm** [comment]
Can you provide some debug output per the README?

**Comment by emilravn** [comment]
Sorry, I should probably redirect this issue to the Docker version since I am running with Docker instead?

**Comment by emilravn** [comment]
I'll try my best to explain what I have done to setup the VPN. Currently it is only made for testing purposes. It is configured on a Linode with Ubuntu 20.04 LTS.

1. Install VPN setup script from [GitHub OpenVPN Script](https://github.com/angristan/openvpn-install) with the automated headless install.
2. Verify connection with OpenVPN by importing the .ovpn-file into my OpenVPN. No issues here.
3. Add `management 127.0.0.0 5555` and `management 0.0.0.0 5555` to `/etc/openvpn/server.conf`
4. Start up the [Docker container](https://github.com/ruimarinho/docker-openvpn-monitor) configured with the IP of the docker container.
5. Accessible through the IP address of the Linode and clients showing up as mentioned in the image.

**Comment by emilravn** [comment]
Unrelated issue, closing the ticket.
