### ISSUE TITLE
Client list blank

### ISSUE THREAD

**Issue by PeteK209** [furlongm/openvpn-monitor#170]
It shows my clients connected and if i run 

python openvpn-monitor.py -d
I get client full info but on the website im not seeign any client info
<img width="1655" alt="Screen Shot 2020-07-14 at 2 07 46 PM" src="https://user-images.githubusercontent.com/18009601/87460877-8f3ef900-c5db-11ea-9f77-7847891cc4c1.png">

debug

shows all the ip's and usernames along with one of these for each connected user

DEBUG:
 === begin split line
deque([u'CLIENT_LIST', u'userid', u'xxx.xxx.xxx.xxx:53125', u'', u'493495', u'40709518', u'Tue Jul 14 13:21:07 2020', u'1594747267', u'UNDEF'])
=== end split line

**Comment by PeteK209** [comment]
by the wya i use TAP anyone can help it woudl be great. love the monitor but would be better if we can see the connected users.

**Comment by furlongm** [comment]
The client info is missing the local ip address, and unfortunately, the local ip address is used as the key. Are these clients getting ip addresses?

**Comment by PeteK209** [comment]
> The client info is missing the local ip address, and unfortunately, the local ip address is used as the key. Are these clients getting ip addresses?

Yes each client has a ip address on the .16 subnet 

I took the Ip out to not show our internal info I replaced it with the x's

**Comment by PeteK209** [comment]
I think your right, so my clients all have there own IPs but im not seeing them in the report but if i check how they are connected to our internal system they have the ips on the subnet they should. How do i fix that?

**Comment by PeteK209** [comment]
so i added

server-bridge 192.168.16.2 255.255.254.0 192.168.16.20 192.168.17.250
push "dhcp-option DNS 192.168.16.31"

to the server conf and after everyone reconnected i could see there username and ip's but noone was ablw to have access to any of our internal websites. 

some machines were connecting to shared drives some werent.

**Comment by PeteK209** [comment]
Could the problem be I didnt include the Second DNS for outside dns?
