### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by dyamicdigitaldesign** [furlongm/openvpn-monitor#174]
Hey,

Ubuntu 20.04
Using Python3
Running OpenVPN and monitor on the same server.

I'm getting an internal server error when loading http://example.com/openvpn-monitor/

Apache2 error log shows these errors on every page reload:
```
[Sun Aug 16 07:06:03.914904 2020] [wsgi:error] [pid 166019] [client 101.177.201.103:57678] mod_wsgi (pid=166019): Failed to exec Python script file '/var/www/html/openvpn-monitor/openvpn-monitor.py'.
[Sun Aug 16 07:06:03.915133 2020] [wsgi:error] [pid 166019] [client 101.177.201.103:57678] mod_wsgi (pid=166019): Exception occurred processing WSGI script '/var/www/html/openvpn-monitor/openvpn-monitor.py'.
[Sun Aug 16 07:06:03.915233 2020] [wsgi:error] [pid 166019] [client 101.177.201.103:57678] Traceback (most recent call last):
[Sun Aug 16 07:06:03.915294 2020] [wsgi:error] [pid 166019] [client 101.177.201.103:57678]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 32, in <module>
[Sun Aug 16 07:06:03.915602 2020] [wsgi:error] [pid 166019] [client 101.177.201.103:57678]     from ipaddress import ip_address
[Sun Aug 16 07:06:03.915681 2020] [wsgi:error] [pid 166019] [client 101.177.201.103:57678] ImportError: No module named ipaddress
```

Debug:
```
INFO: Using config file: ./openvpn-monitor.conf
DEBUG:
 === begin section
{'site': 'Example', 'latitude': '12.46', 'longitude': '130.85', 'maps': 'True', 'geoip_data': '/var/lib/GeoIP/GeoLite2-City.mmdb', 'datetime_format': '%d/%m/%Y %H:%M:%S'}
=== end section
DEBUG:
 === begin section
{'host': 'localhost', 'port': '5555', 'name': 'Dynamic VPN Service', 'show_disconnect': False}
=== end section
WARNING: No compatible geoip1 or geoip2 data/libraries found.
WARNING: socket error: [Errno 111] Connection refused
Content-Type: text/html

<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Example OpenVPN Status Monitor</title>
<meta http-equiv="refresh" content="300" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha256-8uHMIn1ru0GS5KO+zf7Zccf8Uw12IA5DrdEcmMuWLFM=" crossorigin="anonymous" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/css/theme.bootstrap_3.min.css" integrity="sha256-vgjicWNWkVklkfuqKnQth9ww987V7wCOzh6A0qkJ2Lw=" crossorigin="anonymous" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/leaflet/1.6.0/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.6.0/Control.FullScreen.css" integrity="sha256-RTALnHN76PJ32RJx2mxggy+RUt9TIRV+mfPLSLbI75A=" crossorigin="anonymous" />
<style>
.panel-custom {
   background-color:#777;
   color:#fff;
   font-size:80%;
   vertical-align:baseline;
   padding:.4em .4em .4em;
   line-height:1;
   font-weight:700;
}
</style>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.min.js" integrity="sha256-dtGH1XcAyKopMui5x20KnPxuGuSx9Rs6piJB/4Oqu6I=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.widgets.min.js" integrity="sha256-GxbszpUzg+iYIcyDGyNVLz9Y0dQvzmQgXXVk5cHJbw0=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/parsers/parser-network.min.js" integrity="sha256-rV5r5lDTGqNm0Nw6Q/uRKvlco8igIg2PSo3daI1vykA=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script>
<script>$(document).ready(function(){
$("table.tablesorter").tablesorter({sortList: [[0,0]], theme:"bootstrap", headerTemplate:"{content} {icon}", widgets:["uitheme"]});
});</script>
<script src="//cdnjs.cloudflare.com/ajax/libs/leaflet/1.6.0/leaflet.js" integrity="sha256-fNoRrwkP2GuYPbNSJmMJOCyfRB2DhPQe0rGTgzRsyso=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/OverlappingMarkerSpiderfier-Leaflet/0.2.6/oms.min.js" integrity="sha256-t+V41b9l6j8GMYAbpcnZbib1XiYwCAsDibD8sI1D7+Y=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.6.0/Control.FullScreen.min.js" integrity="sha256-6H5xWuqlbGtfk8UL9eMYmp14brCbCw1ZZialT8fHLRE=" crossorigin="anonymous"></script>
</head><body>
<nav class="navbar navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle" 
data-toggle="collapse" data-target="#myNavbar">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">
Example OpenVPN Status Monitor</a>
</div><div class="collapse navbar-collapse" id="myNavbar">
<ul class="nav navbar-nav"><li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">VPN
<span class="caret"></span></a>
<ul class="dropdown-menu">
<li><a href="#dynamic_vpn_service">Dynamic VPN Service</a></li>
</ul></li>
<li><a href="#map_canvas">Map View</a></li>
</ul>
</div></div></nav>
<div class="container-fluid">
<div class="panel panel-danger" id="dynamic_vpn_service">
<div class="panel-heading">
<h3 class="panel-title">Dynamic VPN Service</h3></div>
<div class="panel-body">
Could not connect to 
localhost:5555 (Connection refused)</div></div>
<div class="panel panel-info"><div class="panel-heading">
<h3 class="panel-title">Map View</h3></div><div class="panel-body">
<div id="map_canvas" style="height:500px"></div>
<script type="text/javascript">
var map = L.map("map_canvas", { fullscreenControl: true, fullscreenControlOptions: { position: "topleft" }  });
var centre = L.latLng(12.46, 130.85);
map.setView(centre, 8);
url = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
var layer = new L.TileLayer(url, {});
map.addLayer(layer);
var bounds = L.latLngBounds(centre);
var oms = new OverlappingMarkerSpiderfier (map,{keepSpiderfied:true});
var popup = new L.Popup({closeButton:false,offset:new L.Point(0.5,-24)});
oms.addListener("click", function(marker) {
   popup.setContent(marker.alt);
   popup.setLatLng(marker.getLatLng());
   map.openPopup(popup);
});
oms.addListener("spiderfy", function(markers) {
   map.closePopup();
});
map.fitBounds(bounds);
</script>
</div></div>
<div class="well well-sm">
Page automatically reloads every 5 minutes.
Last update: <b>16/08/2020 07:15:22</b></div>
</div></body></html>
DEBUG:
 === begin vpns
{'VPN1': {'error': 'Connection refused',
          'host': 'localhost',
          'name': 'Dynamic VPN Service',
          'port': '5555',
          'show_disconnect': False,
          'socket_connected': False}}
=== end vpns
```
Can you also please assist with running the monitor on a remote computer? What changes to I make to /etc/openvpn/server/server.config and the status monitor?

**Comment by dyamicdigitaldesign** [comment]
[client 101.177.201.103:57678] 
That IP is the current IP of the computer I'm using. It is not the server running OpenVPN or the monitor.
I'm getting this error whether 101.177.201.103 is connected to the VPN or not.

**Comment by dyamicdigitaldesign** [comment]
Had to run:
```
$ sudo apt remove libapache2-mod-python libapache2-mod-wsgi
$ sudo apt install libapache2-mod-wsgi-py3 python3-bottle
```
to match python versions.

Now I'm able to view the monitor and am getting the errors
Could not conenct lot localhost:5555 (connection refused)```
And in the error.log
```
[Sun Aug 16 07:51:40.833100 2020] [wsgi:error] [pid 167235] [client 101.177.201.103:59528] INFO: Using config file: ./openvpn-monitor.conf
[Sun Aug 16 07:51:40.897202 2020] [wsgi:error] [pid 167235] [client 101.177.201.103:59528] WARNING: No compatible geoip1 or geoip2 data/libraries found.
[Sun Aug 16 07:51:40.901634 2020] [wsgi:error] [pid 167235] [client 101.177.201.103:59528] WARNING: socket error: [Errno 111] Connection refused
```

I'll investigate other issues people have raised on these issues.

**Comment by toxi22** [comment]
I am still getting Error: 500 Internal Server Error.
In the configuration file "openvpn-monitor.conf" I have 64 OpenVPN servers registered. I registered 8 servers - I get the same error after a while or immediately after refreshing the page

Screenshot: [https://prnt.sc/ucembr](https://prnt.sc/ucembr)

`INFO: Sending command: status 3

Traceback (most recent call last):
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "openvpn-monitor.py", line 919, in get_slash
    return render()
  File "openvpn-monitor.py", line 907, in render
    main(**kwargs)
  File "openvpn-monitor.py", line 868, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 223, in collect_data
    status = self.send_command('status 3\n')
  File "openvpn-monitor.py", line 279, in send_command
    socket_data = self._socket_recv(1024)
  File "openvpn-monitor.py", line 234, in _socket_recv
    return self.s.recv(length)
timeout: timed out
[pid: 4818|app: 1|req: 17/28] 195.xxx.xxx.xxx () {72 vars in 1347 bytes} [Sun Sep  6 05:28:37 2020] GET /openvpn-monitor/ => generated 757 bytes in 3230 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
INFO: Using config file: ./openvpn-monitor.conf
WARNING: No compatible geoip1 or geoip2 data/libraries found.
INFO: Sending command: version`

AND

`INFO: Sending command: status 3

Traceback (most recent call last):
  File "/www/openvpn-monitor_mini/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/www/openvpn-monitor_mini/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "openvpn-monitor.py", line 922, in get_slash
    return render()
  File "openvpn-monitor.py", line 910, in render
    main(**kwargs)
  File "openvpn-monitor.py", line 871, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 223, in collect_data
    status = self.send_command('status 3\n')
  File "openvpn-monitor.py", line 279, in send_command
    socket_data = self._socket_recv(1024)
  File "openvpn-monitor.py", line 234, in _socket_recv
    return self.s.recv(length)
timeout: timed out
[pid: 4828|app: 1|req: 9/27] 195.xxx.xxx.xxx () {74 vars in 1331 bytes} [Sun Sep  6 12:33:27 2020] GET /openvpn-status/ => generated 756 bytes in 6537 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)`

**Comment by furlongm** [comment]
@toxi22 can you try the version on this branch: https://github.com/furlongm/openvpn-monitor/tree/socket-timeout

@dyamicdigitaldesign it looks like your issue was python2 vs python3 issues, the other issue requires the openvpn server to have the `management` line in it as per the docs.

**Comment by toxi22** [comment]
@furlongm The page with information does not open at all. Always 500 error.

`[pid: 22549|app: 1|req: 2/4] 195.xxx.xxx.xxx () {72 vars in 1361 bytes} [Wed Sep 16 02:26:35 2020] GET /openvpn-monitor/ => generated 757 bytes in 14 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
INFO: Using config file: ./openvpn-monitor.conf
Traceback (most recent call last):
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "openvpn-monitor.py", line 935, in get_slash
    return render()
  File "openvpn-monitor.py", line 923, in render
    main(**kwargs)
  File "openvpn-monitor.py", line 884, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 216, in collect_data
    ver = self.send_command('version\n')
TypeError: send_command() takes exactly 3 arguments (2 given)
[pid: 22552|app: 1|req: 1/5] 195.xxx.xxx.xxx () {72 vars in 1361 bytes} [Wed Sep 16 02:26:36 2020] GET /openvpn-monitor/ => generated 757 bytes in 65 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
INFO: Using config file: ./openvpn-monitor.conf
Traceback (most recent call last):
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "openvpn-monitor.py", line 935, in get_slash
    return render()
  File "openvpn-monitor.py", line 923, in render
    main(**kwargs)
  File "openvpn-monitor.py", line 884, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 216, in collect_data
    ver = self.send_command('version\n')
TypeError: send_command() takes exactly 3 arguments (2 given)
[pid: 22551|app: 1|req: 3/6] 195.xxx.xxx.xxx () {72 vars in 1361 bytes} [Wed Sep 16 02:26:39 2020] GET /openvpn-monitor/ => generated 757 bytes in 13 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
INFO: Using config file: ./openvpn-monitor.conf
Traceback (most recent call last):
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "openvpn-monitor.py", line 935, in get_slash
    return render()
  File "openvpn-monitor.py", line 923, in render
    main(**kwargs)
  File "openvpn-monitor.py", line 884, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 216, in collect_data
    ver = self.send_command('version\n')
TypeError: send_command() takes exactly 3 arguments (2 given)
[pid: 22549|app: 1|req: 3/7] 195.xxx.xxx.xxx () {72 vars in 1361 bytes} [Wed Sep 16 02:26:41 2020] GET /openvpn-monitor/ => generated 757 bytes in 15 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
INFO: Using config file: ./openvpn-monitor.conf
Traceback (most recent call last):
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "openvpn-monitor.py", line 935, in get_slash
    return render()
  File "openvpn-monitor.py", line 923, in render
    main(**kwargs)
  File "openvpn-monitor.py", line 884, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 216, in collect_data
    ver = self.send_command('version\n')
TypeError: send_command() takes exactly 3 arguments (2 given)
[pid: 22552|app: 1|req: 2/8] 195.xxx.xxx.xxx () {74 vars in 1346 bytes} [Wed Sep 16 02:26:53 2020] GET /openvpn-monitor/ => generated 757 bytes in 16 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)`

**Comment by furlongm** [comment]
Oops, my bad, please try again with the updated file.

**Comment by toxi22** [comment]
> Oops, my bad, please try again with the updated file.

Updated. Does not work. Error 500


Wed Sep 16 03:26:05 2020 - *** Starting uWSGI 2.0.12-debian (64bit) on [Wed Sep 16 03:26:05 2020] ***
Wed Sep 16 03:26:05 2020 - compiled with version: 5.4.0 20160609 on 28 September 2018 15:49:44
Wed Sep 16 03:26:05 2020 - os: Linux-4.4.0-189-generic #219-Ubuntu SMP Tue Aug 11 12:26:50 UTC 2020
Wed Sep 16 03:26:05 2020 - nodename: spb-russia-veesp.vpn.zaborona.help
Wed Sep 16 03:26:05 2020 - machine: x86_64
Wed Sep 16 03:26:05 2020 - clock source: unix
Wed Sep 16 03:26:05 2020 - pcre jit disabled
Wed Sep 16 03:26:05 2020 - detected number of CPU cores: 2
Wed Sep 16 03:26:05 2020 - current working directory: /
Wed Sep 16 03:26:05 2020 - writing pidfile to /run/uwsgi/app/openvpn-monitor/pid
Wed Sep 16 03:26:05 2020 - detected binary path: /usr/bin/uwsgi-core
Wed Sep 16 03:26:05 2020 - *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Wed Sep 16 03:26:05 2020 - chdir() to /www/openvpn-monitor/openvpn-monitor
Wed Sep 16 03:26:05 2020 - your processes number limit is 7829
Wed Sep 16 03:26:05 2020 - your memory page size is 4096 bytes
Wed Sep 16 03:26:05 2020 - detected max file descriptor number: 1024
Wed Sep 16 03:26:05 2020 - lock engine: pthread robust mutexes
Wed Sep 16 03:26:05 2020 - thunder lock: disabled (you can enable it with --thunder-lock)
Wed Sep 16 03:26:05 2020 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/openvpn-monitor/socket fd 3
Wed Sep 16 03:26:05 2020 - Python version: 2.7.12 (default, Jul 21 2020, 15:19:50)  [GCC 5.4.0 20160609]
Wed Sep 16 03:26:05 2020 - Set PythonHome to /www/openvpn-monitor/openvpn-monitor
Wed Sep 16 03:26:05 2020 - *** Python threads support is disabled. You can enable it with --enable-threads ***
Wed Sep 16 03:26:05 2020 - Python main interpreter initialized at 0x113f350
Wed Sep 16 03:26:05 2020 - your server socket listen backlog is limited to 100 connections
Wed Sep 16 03:26:05 2020 - your mercy for graceful operations on workers is 60 seconds
Wed Sep 16 03:26:05 2020 - mapped 363840 bytes (355 KB) for 4 cores
Wed Sep 16 03:26:05 2020 - *** Operational MODE: preforking ***
Wed Sep 16 03:26:05 2020 - WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x113f350 pid: 24128 (default app)
Wed Sep 16 03:26:05 2020 - mounting openvpn-monitor.py on /openvpn-monitor
Wed Sep 16 03:26:05 2020 - WSGI app 1 (mountpoint='/openvpn-monitor') ready in 0 seconds on interpreter 0x1428910 pid: 24128
Wed Sep 16 03:26:05 2020 - *** uWSGI is running in multiple interpreter mode ***
Wed Sep 16 03:26:05 2020 - spawned uWSGI master process (pid: 24128)
Wed Sep 16 03:26:05 2020 - spawned uWSGI worker 1 (pid: 24243, cores: 1)
Wed Sep 16 03:26:05 2020 - spawned uWSGI worker 2 (pid: 24244, cores: 1)
Wed Sep 16 03:26:05 2020 - spawned uWSGI worker 3 (pid: 24245, cores: 1)
Wed Sep 16 03:26:05 2020 - spawned uWSGI worker 4 (pid: 24246, cores: 1)
INFO: Using config file: ./openvpn-monitor.conf
INFO: Sending command: version

Traceback (most recent call last):
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "openvpn-monitor.py", line 935, in get_slash
    return render()
  File "openvpn-monitor.py", line 923, in render
    main(**kwargs)
  File "openvpn-monitor.py", line 884, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 218, in collect_data
    vpn['version'] = semver(vpn, vpn['release'].split(' ')[1])
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/semantic_version/base.py", line 77, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/semantic_version/base.py", line 203, in parse
    match = version_re.match(version_string)
TypeError: expected string or buffer
[pid: 24243|app: 1|req: 1/1] 195.211.175.81 () {70 vars in 1280 bytes} [Wed Sep 16 03:26:32 2020] GET /openvpn-monitor/ => generated 757 bytes in 35 msecs (HTTP/1.1 500) 2 headers in 99 bytes (2 switches on core 0)
INFO: Using config file: ./openvpn-monitor.conf
INFO: Sending command: version

Traceback (most recent call last):
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "openvpn-monitor.py", line 935, in get_slash
    return render()
  File "openvpn-monitor.py", line 923, in render
    main(**kwargs)
  File "openvpn-monitor.py", line 884, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 218, in collect_data
    vpn['version'] = semver(vpn, vpn['release'].split(' ')[1])
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/semantic_version/base.py", line 77, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/www/openvpn-monitor/openvpn-monitor/local/lib/python2.7/site-packages/semantic_version/base.py", line 203, in parse
    match = version_re.match(version_string)
TypeError: expected string or buffer
[pid: 24243|app: 1|req: 2/2] 195.211.175.81 () {74 vars in 1333 bytes} [Wed Sep 16 03:26:34 2020] GET /openvpn-monitor/ => generated 757 bytes in 11 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)

**Comment by furlongm** [comment]
I fixed that, please try again now.

**Comment by toxi22** [comment]
@furlongm Thank you, it works.

**Comment by furlongm** [comment]
How often are you updating? The openvpn server can only handle one concurrent connection to management interface IIUC.

**Comment by toxi22** [comment]
> How often are you updating? The openvpn server can only handle one concurrent connection to management interface IIUC.

Usually once every five minutes.
Tried updating once every minute - error 500 appears.

**Comment by toxi22** [comment]
The page was opened within 30 minutes and 500 error appeared again:

LOG:

INFO: Sending command: state

INFO: Sending command: load-stats

INFO: Sending command: status 3

WARNING: socket timeout: timed out
Traceback (most recent call last):
  File "/www/openvpn-monitor_mini/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/www/openvpn-monitor_mini/openvpn-monitor/local/lib/python2.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "openvpn-monitor.py", line 941, in get_slash
    return render()
  File "openvpn-monitor.py", line 929, in render
    main(**kwargs)
  File "openvpn-monitor.py", line 890, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 223, in collect_data
    status = self.send_command(vpn, 'status 3\n')
  File "openvpn-monitor.py", line 296, in send_command
    socket_data = re.sub('>INFO(.)*\r\n', '', socket_data)
  File "/www/openvpn-monitor_mini/openvpn-monitor/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[pid: 1788|app: 1|req: 369/753] 94.242.59.156 () {34 vars in 366 bytes} [Fri Sep 18 16:20:01 2020] GET /openvpn-status/ => generated 755 bytes in 12099 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)

**Comment by furlongm** [comment]
Is there more than one client accessing the server?

**Comment by toxi22** [comment]
> Is there more than one client accessing the server?

During test 1 client connected

**Comment by septatrix** [comment]
Is it somehow possible to have multiple clients access the page at the same time? Currently I run into collisions occasionally. Would it be possible to add a global lock, always close the socket or disable multithreading in `mod_wsgi`?

**Comment by septatrix** [comment]
Or just read the status file which should contain the same information (just maybe not as recent)?

**Comment by toxi22** [comment]
> Or just read the status file which should contain the same information (just maybe not as recent)?

I made for myself the generation of a static file that is updated every 5 minutes via the system cron.
`*/5 * * * * curl -l http://127.0.0.1/openvpn-status/ > /www/mysitehelp/srv-mon.html`
And I am already addressing the generated file directly: http://mysitehelp/srv-mon.html

**Comment by fedor-git** [comment]
Hi guys. I have similar situation but in docker container.

**Comment by furlongm** [comment]
@fedor-git  can you try to apply d114d7959162a47eaf304688b1dc0eb05ead2b0c and see if that helps?

**Comment by furlongm** [comment]
This should be handled better in v2. Feel free to reopen if it still occurs

**Comment by septatrix** [comment]
> This should be handled better in v2. Feel free to reopen if it still occurs

Is there a changelog for all things in v2?
