### ISSUE TITLE
IP information not displaying

### ISSUE THREAD

**Issue by wagnerjsilva** [furlongm/openvpn-monitor#177]
Hello, 

For some reason I'm not getting the IP information on my apache setup 

![image](https://user-images.githubusercontent.com/2353544/92130678-ebb0de80-edfc-11ea-8172-351173e78a21.png)

Any ideas on what I can be doing wrong?

**Comment by furlongm** [comment]
If you run in debug mode on the command line, does it show any geoip warnings?

**Comment by wagnerjsilva** [comment]
Hi,

I think we are in the right track, I get this: 

WARNING: No compatible geoip1 or geoip2 data/libraries found.

The software is being run from: 

/home/ubuntu/lib/python2.7/site-packages

Any more clues?

**Comment by furlongm** [comment]
You would need to install geoip libraries per the installation guide. I'll close this - let me know if the instructions there don't work.
