### ISSUE TITLE
Can I configure the view of the openvpn-monitor page through nginx so that several people can view this page at the same time? 

### ISSUE THREAD

**Issue by toxi22** [furlongm/openvpn-monitor#180]
Hello!
Can I configure the view of the openvpn-monitor page through nginx so that several people can view this page at the same time? Do you have any recommendations for setting up? Maybe the openvpn-monitor script itself can display information to several users at the same time?

At this time, I see an option like this:
Cron runs the curl command on the server every 5 minutes, opens the openvpn-monitor page, takes a screenshot or renders the page in html format and puts it in a temporary folder on disk or in RAM and nginx gives the user a ready-made page.

**Comment by furlongm** [comment]
IIUC openvpn only allows one connection to the TCP/IP management interface at a time. You could try using a socket instead and see if that allows more than one client concurrently?

**Comment by furlongm** [comment]
Did using a socket help?

**Comment by furlongm** [comment]
Closing due to no response. Feel free to reopen if the issue persists.
