### ISSUE TITLE
netdata and monitor 500 Internal

### ISSUE THREAD

**Issue by free514** [furlongm/openvpn-monitor#187]
i turn on netdata with access to openvpn management

and monitor stop working 

show 500 Internal Server Error
or show Could not connect to localhost:5555 (timed out)

**Comment by free514** [comment]
/srv/openvpn-monitor# python openvpn-monitor.py
Traceback (most recent call last):
  File "openvpn-monitor.py", line 32, in <module>
    from ipaddress import ip_address
ImportError: No module named ipaddress

**Comment by free514** [comment]
is because openvpn management not accept  two connections one from openvpnmonitor and other from netadata?

there is anyway accept two connections?

**Comment by furlongm** [comment]
openvpn can only accept one connection over tcp/ip - you could try a using a socket for a second connection?
