### ISSUE TITLE
Feature request: sorted output

### ISSUE THREAD

**Issue by Meisterschueler** [furlongm/openvpn-monitor#19]
My VPN is growing and for a better overview I need a sorted output for "Username / Hostname" or "VPN IP Address". At the moment the output is not sorted at all, right? As a first step you could introduce a default sorting for "Username / Hostname". In a second step you could introduce a user defined sorting.

**Comment by kidmock** [comment]
Maybe not what you are looking for but this works for me.

change 
```diff
    def print_session_table(self, vpn_mode, sessions):
        for key, session in list(sessions.items()):
```
to
```
    def print_session_table(self, vpn_mode, sessions):
        for key, session in sorted(sessions.items()):
```

**Comment by Meisterschueler** [comment]
Thank you! Works for most fields but not for VPN IP address:
![bildschirmfoto 2016-12-16 um 09 14 53](https://cloud.githubusercontent.com/assets/4268343/21256079/5c46b978-c370-11e6-83f8-146f715f2f24.png)

**Comment by furlongm** [comment]
I think we need to wait for the fix in https://github.com/christianbach/tablesorter/issues/106 to be merged.

**Comment by Mottie** [comment]
You're actually using my [fork of tablesorter](https://github.com/Mottie/tablesorter)... so the IP parser should work as expected. I can tell because the script is pointing to v2.28.1 on CDNJS. The original is still stuck on v2.0.5b.

**Comment by furlongm** [comment]
@Mottie does parser-network.js need to be included separately? I've browsed the documentation but it's not clear to me how to do this.

**Comment by Mottie** [comment]
Yes, include the "parser-network.js" file after loading tablesorter.

```html
<script src="jquery.min.js"></script>
<script src="jquery.tablesorter.min.js"></script>
<!-- include widgets? -->
<script src="parser-network.min.js"></script>
```

The "ipAddress" parser will auto-detect and set the parser for the column. You can also set it by adding a "sorter-ipAddress" class name on the header.

**Comment by furlongm** [comment]
@Meisterschueler can you confirm if this commit the issue for you?

**Comment by furlongm** [comment]
@Meisterschueler can you confirm if commit 4615cdeec89973606b1f026b38db47628da0d433 fixes the issue for you?

**Comment by Meisterschueler** [comment]
I get another error:
`INFO: Using config file: ./openvpn-monitor.conf
Traceback (most recent call last):
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 724, in <module>
    main()
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 702, in main
    OpenvpnHtmlPrinter(cfg, monitor)
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 405, in __init__
    self.print_vpn(key, vpn)
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 590, in print_vpn
    self.print_session_table(vpn_id, vpn_mode, vpn_sessions, show_disconnect)
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 659, in print_session_table
    self.print_server_session(vpn_id, session, show_disconnect)
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 626, in print_server_session
    output('<td><img src="{0!s}" title="{1!s}" alt="{1!s}" /> '.format(flag, full_location))
UnboundLocalError: local variable 'full_location' referenced before assignment`

**Comment by furlongm** [comment]
@Meisterschueler that should be fixed now too, can you try the latest commit?

**Comment by Meisterschueler** [comment]
The file "images/flags/rfc1918.png" is missing

**Comment by furlongm** [comment]
This should be fixed now, try a03ee445c6e5224fed6b66efa54b009ce1b3546f

**Comment by Meisterschueler** [comment]
Thank you, now it works perfectly!

**Comment by furlongm** [comment]
Good to hear! 👍
