### ISSUE TITLE
Had to change this line in order to get it to work on ubuntu 20.04

### ISSUE THREAD

**Issue by wblotevogel** [furlongm/openvpn-monitor#190]
Not an issue. Just a comment.

https://github.com/furlongm/openvpn-monitor/blob/c28d67ed738c0d7083922a43919e08b1d72d8496/openvpn-monitor.py#L1

Had to change it into:

`#!/usr/bin/python3`

Then it worked.

**Comment by furlongm** [comment]
Thanks - please check out the `develop` branch for newer distros!

**Comment by arthur4ires** [comment]
I change it on my fork, thank you!
