### ISSUE TITLE
Openvpn-monitor only trough vpn

### ISSUE THREAD

**Issue by PrzemekSkw** [furlongm/openvpn-monitor#197]
Hello, what is the best way to install openvpn-monitor to work only on openvpn clients with my vpn ip 10.8.0.1?
I install with:
```
mkdir /srv/openvpn-monitor
cd /srv/openvpn-monitor
virtualenv .
. bin/activate
pip install --upgrade pip
pip install openvpn-monitor gunicorn
gunicorn openvpn-monitor -b 10.8.0.1:8080
```
and it works just like I want but stop when I close terminal. How to add it to work all the time in Debian?

Regards,
Przemek

**Comment by furlongm** [comment]
This might help you: https://docs.gunicorn.org/en/stable/deploy.html#systemd
