### ISSUE TITLE
Location not correct?

### ISSUE THREAD

**Issue by o0Sovjet0o** [furlongm/openvpn-monitor#20]
Hello,

I got everything working 👍 

The only problem i encounter is that the location is not correct, its show my location and friends that live in my city that they are almost 6 or 7 kilometer from their real location

Did i do something wrong or is this because of privacy reasons ??

Kind Regards

Sovjet

**Comment by furlongm** [comment]
Hi,

This is due to using the free external geoip database provided by Maxmind. You could try updating the database as per the instructions, but the locations will still be approximate.

**Comment by o0Sovjet0o** [comment]
Thanks i will try that, thanks for the fast reply 👍.
