### ISSUE TITLE
500 Internal Server Error - 

### ISSUE THREAD

**Issue by adrigsby** [furlongm/openvpn-monitor#206]
Scenario: 
1. Openvpn program running on Raspberry Pi. (2 active test clients).
2. Openvpn-monitor installed but the HTML generated doesn't display on the webpage http://x.x.x.x

html generated using: python openvpn-monitor.py
no error
[html1.txt](https://github.com/furlongm/openvpn-monitor/files/6406284/html1.txt)

html generated using: sudo python openvpn-monitor.py
pi@raspberrypi:/var/www/html/openvpn-monitor $ sudo python openvpn-monitor.py
Traceback (most recent call last):
  File "openvpn-monitor.py", line 41, in <module>
    from geoip2 import database
  File "/usr/local/lib/python2.7/dist-packages/geoip2/database.py", line 9, in <module>
    import maxminddb
  File "/usr/local/lib/python2.7/dist-packages/geoip2/maxminddb/__init__.py", line 4, in <module>
    import maxminddb.reader
  File "/usr/local/lib/python2.7/dist-packages/maxminddb/__init__.py", line 25
    datbase: Union[AnyStr, int, os.PathLike, IO], mode: int = MODE_AUTO
           ^
SyntaxError: invalid syntax

Question(s) - 1. Openvpn configuration assistance to populate the web browser.
                      2. Is this a permission issue between accounts root and pi (root privileges)?
                    
Thanks for any/all help with this...

**Comment by JohanPotgieter** [comment]
I also had this issue. Run it with python 3.5/3.7

**Comment by furlongm** [comment]
As noted, please use `python3` instead of `python`
