### ISSUE TITLE
Suggestion - Date format

### ISSUE THREAD

**Issue by kidmock** [furlongm/openvpn-monitor#22]
Since I live in the United States, the date format is sometimes confusing for my junior team members.

The US uses Month/Day/Year and this tool uses Day/Month/Year. Without being aware of the date format some folks get confused for example 10/12/2016 in Australia is December 10th but the US it's October 12th.

I really have no issues making the localized modifications, Perhaps you might want to consider a localization option or using ISO 8601 (YYYY-MM-DD) by default .

Keep up the great work

**Comment by furlongm** [comment]
You can use any of the strftime directives at http://strftime.org/
