### ISSUE TITLE
Geoip-database-extra Issue

### ISSUE THREAD

**Issue by zafer-cigdem** [furlongm/openvpn-monitor#220]
Hello Marcus @furlongm ,

Thank you for the program!

I have a similiar error as [https://github.com/furlongm/openvpn-monitor/issues/158](158)

I am using **Ubuntu 20.04 (LTS) x64**. The steps that I completed are:

- installing OpenVP 
- installing Apache 
- installing PHP
- use instruction for apache Debian / Ubuntu version from your Github.

I already tried your advice (using "developmen branch"), but I still receive same error which is:

Package geoip-database-extra is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source

I googled and try to use some alternative way, but it does not work. Please let me know if you have any advice to me. If you want me to share any output I'll be happy to share. Thank you again!

P.S. When I try to use "nginx + uwsgi" instead of Apache, I receive same error.

**Comment by furlongm** [comment]
New version released now, please see if that still has the same issue.
