### ISSUE TITLE
ubuntu 20.04 OpenVPN fresh setup - unable to locate packages (geo***, python***)

### ISSUE THREAD

**Issue by jam-2000** [furlongm/openvpn-monitor#221]
Hi

Fresh install OpenVPN (angristan) on fresh Ubuntu LTS  20.04.3
There are a problems with installation of such required packages:
E: Unable to locate package python-geoip2
E: Unable to locate package python-ipaddr
E: Unable to locate package python-humanize
E: Unable to locate package python-bottle
E: Unable to locate package python-semantic-version
E: Package 'geoip-database-extra' has no installation candidate

3 years ago i found this project and used it till this days without any troubles(ubuntu 16.04)
Few days ago my server crashed because of hardware failure
So i installed new one with ubuntu 20.04.3 and was surprised with errors when tried to install openvpn-monitor from here

Can you please help with some fix 
I do like this project and hope it will be fixed soon

Thanks a lot in advance!!!

**Comment by furlongm** [comment]
New version released now, please try that.
