### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by IntelligenceHostingLLC** [furlongm/openvpn-monitor#226]
How do you parse the connected users? I only want to know how to do that as I'm trying to work on a way to hide the ips and stuff.

**Comment by BrinzaBezrukoff** [comment]
This tool is using [management interface](https://openvpn.net/community-resources/management-interface/) of OpenVPN server. You can open this interface with `telnet localhost <port>` (don't forget to add management interface in openvpn server config). There is command `status` that can show client list.
![изображение](https://github.com/furlongm/openvpn-monitor/assets/29017599/7461e461-761c-4754-95b4-67d3b1b16767)

**Comment by furlongm** [comment]
Question answered
