### ISSUE TITLE
CLIENT_LIST instead of username in "Username/Hostname" table

### ISSUE THREAD

**Issue by elapse2039** [furlongm/openvpn-monitor#25]
I have installed openvpn-monitor via the quick install method in the README.  It runs, and I see "CLIENT_LIST" in the Username/Hostname field for all users.  Any idea why this is not the name of the actual user/host that is connected?

**Comment by furlongm** [comment]
What version of openvpn are you using?

**Comment by elapse2039** [comment]
OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Feb 2 2016 running on Ubuntu 16.04 server.

**Comment by furlongm** [comment]
Could you paste the output of running in debug mode?

**Comment by elapse2039** [comment]
[openvpn-monitor-debug.txt](https://github.com/furlongm/openvpn-monitor/files/681621/openvpn-monitor-debug.txt)

**Comment by furlongm** [comment]
Thanks, can you also give the output of `python openvpn-monitor.py -d` ?

**Comment by furlongm** [comment]
I've uploaded a more recent version to pypi. There have been quite a few changes since I updated there version there. Can you try with the latest version?

`pip install -U openvpn-monitor` in the virtualenv should be sufficient to upgrade.

**Comment by elapse2039** [comment]
Thanks! This upgrade to openvpn-monitor-1.0.0rc18 worked using gunicorn to launch openvpn-monitor.  The Username/Hostname appears now in the table.  (I still can't get openvpn-monitor to launch via apache2 instructions above on U16.04 but will stick with gunicorn for now).
