### ISSUE TITLE
Stop during installation

### ISSUE THREAD

**Issue by shahrooz1349** [furlongm/openvpn-monitor#257]
![Screenshot_20220813_191845](https://user-images.githubusercontent.com/87688187/184499421-296b1298-c24e-4320-a71e-ee941b2d927d.jpg)
Hello Friends, the installation will stop at this stage.
debian 10
regard

**Comment by ercholo** [comment]
gunicorn openvpn-monitor -b 0.0.0.0:80 --name openvpn-monitor --daemon

**Comment by shahrooz1349** [comment]
> gunicorn openvpn-monitor -b 0.0.0.0:80 --name openvpn-monitor --daemon

tnx my friend
