### ISSUE TITLE
Need updated instructions for Ubuntu 20.04

### ISSUE THREAD

**Issue by Tennyleaz** [furlongm/openvpn-monitor#258]
The ubuntu/debain install command was:
```
apt -y install git apache2 libapache2-mod-wsgi python3-geoip2 python3-humanize python3-bottle python3-semantic-version geoip-database geoip-database-extra
```
But `libapache2-mod-wsgi` cannot properly execute python3 scripts. It should be replaced by `libapache2-mod-wsgi-py3`.
Also ubuntu 20.04 does not include `geoip-database-extra` package anymore.

**Comment by nounours460** [comment]
Hi,

libapache2-mod-wsgi => libapache2-mod-wsgi-py3
geoip-database-extra => geoip-database

Good luck

**Comment by rubenvg95** [comment]
Thanks!! Instructions must me updated

**Comment by furlongm** [comment]
Instructions updated
