### ISSUE TITLE
How to load the tool on Ubuntu 14.04  

### ISSUE THREAD

**Issue by rchcoffey1** [furlongm/openvpn-monitor#259]
Hi all before I was able to have the tool run on a ubuntu 14.04 server with python 2.7, now when I try to load the tool on a new ubuntu 14.4 server I can't load the python files that are needed ( can't find them, apt doesn't work, pip isn't working ). I can't upgrade to ubuntu 20.04. 

Please help

**Comment by furlongm** [comment]
Ubuntu 14:04 is no longer supported:

https://github.com/furlongm/openvpn-monitor#supported-operating-systems
