### ISSUE TITLE
flags wont load and the city is double 

### ISSUE THREAD

**Issue by rchcoffey1** [furlongm/openvpn-monitor#262]
hi, flags won't load and the city name is doubled ... i check the apache log and it states a scrip error ... and I put the / tailing the URL .. please help

**Comment by rchcoffey1** [comment]
(13)Permission denied: AH01241: exec of '/var/www/html/openvpn-monitor/images/flags/us.png' failed[client 10.50.50.6:52958] End of script output before headers: us.png, referer: http://10.50.50.1/

**Comment by galavichid** [comment]
Try this in your /etc/apache2/sites-enabled/openvpn-monitor.conf

ScriptAlias / /var/www/html/openvpn-monitor/openvpn-monitor.py
        <Directory /var/www/html/openvpn-monitor>
                Options +ExecCGI
                DirectoryIndex openvpn-monitor.py
                Order allow,deny
        Allow from all
        AddHandler default-handler .jpg .png
        Require ip <yoursubnet>/24
        </Directory>
