### ISSUE TITLE
Still support for this tool?

### ISSUE THREAD

**Issue by Individuum92** [furlongm/openvpn-monitor#263]
Hi,

After I have everything, when I go to the page, it just displays the entire Python script in plain text. How can I fix this?
I followed the instructions below because unfortunately there are problems with the commands given here:

https://kifarunix.com/how-to-monitor-openvpn-connections-using-openvpn-monitor-tool/

Unfortunately, I see some unresolved requests. Is there still support for this?

**Comment by furlongm** [comment]
Please try the latest release, and let me know if you still have the same issue
