### ISSUE TITLE
[Q+A] Monitoring 100 isolated groups

### ISSUE THREAD

**Issue by PizzaProgram** [furlongm/openvpn-monitor#268]
Hi,

Is it possible to monitor more services running on the same server and see ALL clients together in all those separated groups?
If not, how do I separate groups so I can see all clients as "master group" with this software?

Thank you very much in forward!

## More info:
I need to manage 100+ pizzerias. 
 - Those have each 1-10 windows PC + some iOS/Android phones + some Macs.  
 - Those groups should never be able to reach each other.  
 - I need a master group to "see them all".
 - No connection is allowed to go to the internet through those groups.  
 - Some groups should be able to reach some services on the server. (SQL, Mqtt, ... )  
 - Debian 11, 64 bit, VPS, fix IP, Webmin + "[OpenVPN-Administrator v3.3](https://github.com/a-schild/webmin-openvpn-debian-jessie)" module installed.  

![kép](https://user-images.githubusercontent.com/26026089/228226833-3acea74c-7b71-433a-a5e5-023c050f1f82.png)

**Comment by furlongm** [comment]
This should be possible. Just add the various VPNs. Let me know if it works with v2 for you
