### ISSUE TITLE
Apache opening with contents of openvpn-monitor.py file

### ISSUE THREAD

**Issue by lslamp** [furlongm/openvpn-monitor#271]
I have been trying to figure this out for nearly 2 weeks now. Each time I have the same issue. There is something that I am missing or done wrong.
I am running Ubuntu 22.04 with  Apache/2.4.52.
When I open the URL http://ipaddress/iopenvpn-monitor the site opens to the contents of the openvpn-monitor.py file.

![image](https://github.com/furlongm/openvpn-monitor/assets/6013759/0b9e97c0-7635-4259-8eaa-63afdc4191ee)

Does anyone have any ideas.
below is my openvpn-monitor.conf file

[openvpn-monitor]
site=VPNServerName
#logo=logo.jpg
#latitude=40.72
#longitude=-74
maps=True
maps_height=500
geoip_data=/var/lib/GeoIP/GeoLite2-City.mmdb
datetime_format=%d/%m/%Y %H:%M:%S

[VPN1]
host=localhost
port=17562
name=Staff VPN
show_disconnect=False

**Comment by lslamp** [comment]
I resolved the issue by doing the following. These instructions were not clear.

apt-get install libapache2-mod-cgi
ln -s /etc/apache2/mods-available/cgi.load /etc/apache2/mods-enabled/

Restarted apache2.

But right now I am trying to understand how to get the map co-ordinates to open the URL to the correct location.

Any ideas would help.
Thanks
Lawrence

**Comment by linuxandos2** [comment]
download: https://mirrors.piconets.webwerks.in/archlinux-mirror/extra/os/x86_64/geoip-database-extra-20230901-1-any.pkg.tar.zst
unpack to /usr/share/GeoIP (root user)

in openvpn-monitor.conf file
change  _geoip_data=/var/lib/GeoIP/GeoLite2-City.mmdb_
to          geoip_data=/usr/share/GeoIP/GeoLite2-City.mmdb

**Comment by furlongm** [comment]
Looks like this was resolved
