### ISSUE TITLE
geoip-database-extra

### ISSUE THREAD

**Issue by Itsisme** [furlongm/openvpn-monitor#272]
Hai,

On my ubuntu box I am still missing this:

sudo apt install geoip-database-extra
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package geoip-database-extra is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'geoip-database-extra' has no installation candidate

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

What am I missing who can help me as this looks like a great monitor tool?

Cheers P.

**Comment by Alberto3008** [comment]
Same issue.

**Comment by DanielMM-dev** [comment]
Same issue !

**Comment by linuxandos2** [comment]
download: https://mirrors.piconets.webwerks.in/archlinux-mirror/extra/os/x86_64/geoip-database-extra-20230901-1-any.pkg.tar.zst
unpack to /usr/share/GeoIP (root user)
