### ISSUE TITLE
The map cannot be displayed

### ISSUE THREAD

**Issue by AEGEGE** [furlongm/openvpn-monitor#274]
VPN monitoring and data acquisition are normal, but the map cannot be displayed.
![xxxx](https://github.com/furlongm/openvpn-monitor/assets/20395332/2d309535-fe58-400f-b06b-db2988451fc3)

**Comment by linuxandos2** [comment]
please post your openvpn-monitor.conf
#latitude=40.72
#longitude=-74
should be uncommented
