### ISSUE TITLE
is this project still supported

### ISSUE THREAD

**Issue by sysadminpower2019** [furlongm/openvpn-monitor#280]
it has been several years since the last update

**Comment by JedMeister** [comment]
I'd be interested in an explicit answer to this question too. Although looking at the repo I think the answer is no:
- last release: [Feb 24, 2021](https://github.com/furlongm/openvpn-monitor/releases)
- last commit/merge: [Aug 7, 2022](https://github.com/furlongm/openvpn-monitor/commits/master/)
- latest version of python supported by automated linting: [v3.9](https://github.com/furlongm/openvpn-monitor/blob/master/.github/workflows/lint.yml) (still supported upstream but pretty old now...)
- no response to any recent [issues](https://github.com/furlongm/openvpn-monitor/issues) (inc this one) or [PRs](https://github.com/furlongm/openvpn-monitor/pulls)

Unfortunate cause it looks cool...

**Comment by furlongm** [comment]
It is still supported, please check out the latest release.
