### ISSUE TITLE
Debian12: The repository does not have a Release file.

### ISSUE THREAD

**Issue by muradurm** [furlongm/openvpn-monitor#297]
Err:9 https://repo.openbytes.ie/openvpn-monitor/debian bookworm Release
  404  Not Found [IP: 2a00:dcc0:dead:a05b::1 443]

The repository 'https://repo.openbytes.ie/openvpn-monitor/debian bookworm Release' does not have a Release file.

**Comment by furlongm** [comment]
This should be fixed now
