### ISSUE TITLE
ImportError: No module named semantic_version

### ISSUE THREAD

**Issue by nthool** [furlongm/openvpn-monitor#31]
Hi,

I followed the instructions to install openvpn-monitor, during the debugging process I find an error like this.

```
python openvpn-monitor.py 
Traceback (most recent call last):
   File "openvpn-monitor.py", line 35, in <module>
     from semantic_version import Version as semver
 ImportError: No module named semantic_version
```

I use:
Ubuntu 14.04 LTS
Apache 2.4.7 (Ubuntu)
Python 2.7.6

I hope you can help me. Thanks.

**Comment by furlongm** [comment]
Hmm, on Ubuntu Trusty, you might to use `pip install semantic_version`.

Ubuntu Xenial should be fine.

Can you see if that helps?

**Comment by nthool** [comment]
thanks for your help, I've resolved the issue, but later I get a new problem related to the previous issue (connection refused). but the issue has also been resolved.

Currently I'm waiting for the development of the features found on the list of issues.

Nice work for you @furlongm. I hope openvpn-monitor can grow better.

Best Regards,
nthool

**Comment by furlongm** [comment]
Ok great, I'll close off this issue.
