### ISSUE TITLE
Problem with python

### ISSUE THREAD

**Issue by dfrechilla** [furlongm/openvpn-monitor#32]
Dear furlong!

With Ubuntu 16.04.1 LTS apache shutting down.

/var/log/apache2/error.log

[Thu Feb 02 12:28:17.846459 2017] [mpm_event:notice] [pid 2186:tid 140591778240384] AH00491: caught SIGTERM, shutting down
[Thu Feb 02 12:28:18.876525 2017] [wsgi:warn] [pid 2344:tid 140365205100416] mod_wsgi: Compiled for Python/2.7.11.
[Thu Feb 02 12:28:18.876585 2017] [wsgi:warn] [pid 2344:tid 140365205100416] mod_wsgi: Runtime using Python/2.7.12.
[Thu Feb 02 12:28:18.877273 2017] [mpm_event:notice] [pid 2344:tid 140365205100416] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming$
[Thu Feb 02 12:28:18.877300 2017] [core:notice] [pid 2344:tid 140365205100416] AH00094: Command line: '/usr/sbin/apache2'

Regards,
David.

**Comment by furlongm** [comment]
That output is normal. SIGTERM is sent when you restart apache.
