### ISSUE TITLE
Rename  	openvpn-monitor.conf

### ISSUE THREAD

**Issue by TerAnYu** [furlongm/openvpn-monitor#33]
Please rename **openvpn-monitor.conf** to **openvpn-monitor.conf.example**
It will allow to update the local version from a repository.

**Comment by lyndon160** [comment]
That sounds like you just want to stash your local version when you update your repository.

**Comment by TerAnYu** [comment]
Yes.
It is made in some applications and scripts that when updating all application the changed version was not removed.
