### ISSUE TITLE
GeoIP extension build fails during setup

### ISSUE THREAD

**Issue by maxgrass** [furlongm/openvpn-monitor#35]
Ubuntu 16.10
While repeating "Quick steps":
```
py_GeoIP.c:23:19: fatal error: GeoIP.h: No such file or directory
     #include "GeoIP.h"
                       ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

![Screenshot](https://i.imgur.com/WU0CzSE.png)

**Comment by qzcrown** [comment]
GeoIP missing, plz install it
`
sudo apt-get install libgeoip-dev 
`

**Comment by maxgrass** [comment]
yep

**Comment by timdonovanuk** [comment]
So much for the quick start guide. Maybe include this kinda-sorta-super-important information in the install guide...
