### ISSUE TITLE
Error: 500 Internal Server Error (Synology NAS)

### ISSUE THREAD

**Issue by mdthejericho** [furlongm/openvpn-monitor#37]
VPN server on Synology DS 214
OpenVPN : 1.3.5-2757 (most up to date version in the package center)
Monitor Tool: A VM on the same VPN (10.10.22.14)

Seeing the following errors. Looks like the IP has some extra characters maybe due to the Synology flavor of OpenVPN? 

DEBUG:
 === begin split line
deque([u'TITLE', u'OpenVPN 2.3.11 armle-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [MH] [IPv6] built on Jan 13 2017'])
=== end split line
DEBUG:
 === begin split line
deque([u'TIME', u'Thu Mar  2 23:59:30 2017', u'1488517170'])
=== end split line
DEBUG:
 === begin split line
deque([u'HEADER', u'CLIENT_LIST', u'Common Name', u'Real Address', u'Virtual Address', u'Bytes Received', u'Bytes Sent', u'Connected Since', u'Connected Since (time_t)', u'Username'])
=== end split line
DEBUG:
 === begin split line
deque([u'CLIENT_LIST', u'user', u'::ffff:71.230.XXX.XX(1194)', u'10.10.22.18', u'452352', u'529252', u'Thu Mar  2 23:38:23 2017', u'1488515903', u'user'])
=== end split line
Traceback (most recent call last):
  File "openvpn-monitor.py", line 746, in <module>
    main()
  File "openvpn-monitor.py", line 723, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 170, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 182, in collect_data
    vpn['sessions'] = self.parse_status(status, self.gi, vpn['semver'])
  File "openvpn-monitor.py", line 346, in parse_status
    remote_ip = ip_address(remote)
  File "/usr/lib/python2.7/dist-packages/ipaddr.py", line 78, in IPAddress
    address)
ValueError: u'::ffff:71.230.XXX.XX(1194)' does not appear to be an IPv4 or IPv6 address

[Thu Mar 02 23:55:58.982122 2017] [core:notice] [pid 9503] AH00094: Command line: '/usr/sbin/apache2'
[Thu Mar 02 23:57:17.333137 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497] Traceback (most recent call last):
[Thu Mar 02 23:57:17.333199 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]   File "/usr/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
[Thu Mar 02 23:57:17.333206 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]     return route.call(**args)
[Thu Mar 02 23:57:17.333210 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]   File "/usr/lib/python2.7/dist-packages/bottle.py", line 1737, in wrapper
[Thu Mar 02 23:57:17.333215 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]     rv = callback(*a, **ka)
[Thu Mar 02 23:57:17.333219 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 771, in get_slash
[Thu Mar 02 23:57:17.333224 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]     return render()
[Thu Mar 02 23:57:17.333228 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 784, in render
[Thu Mar 02 23:57:17.333233 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]     main(**kwargs)
[Thu Mar 02 23:57:17.333237 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 723, in main
[Thu Mar 02 23:57:17.333242 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]     monitor = OpenvpnMgmtInterface(cfg, **kwargs)
[Thu Mar 02 23:57:17.333246 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 170, in __init__
[Thu Mar 02 23:57:17.333251 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]     self.collect_data(vpn)
[Thu Mar 02 23:57:17.333255 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 182, in collect_data
[Thu Mar 02 23:57:17.333260 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]     vpn['sessions'] = self.parse_status(status, self.gi, vpn['semver'])
[Thu Mar 02 23:57:17.333264 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 346, in parse_status
[Thu Mar 02 23:57:17.333269 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]     remote_ip = ip_address(remote)
[Thu Mar 02 23:57:17.333273 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]   File "/usr/lib/python2.7/dist-packages/ipaddr.py", line 78, in IPAddress
[Thu Mar 02 23:57:17.333277 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497]     address)
[Thu Mar 02 23:57:17.333282 2017] [wsgi:error] [pid 9508] [client 192.168.1.53:14497] ValueError: '::ffff:71.230.162.47(1194)' does not appear to be an IPv4 or IPv6 address
[Thu Mar 02 23:57:25.320587 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499] Traceback (most recent call last):
[Thu Mar 02 23:57:25.320649 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]   File "/usr/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
[Thu Mar 02 23:57:25.320656 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]     return route.call(**args)
[Thu Mar 02 23:57:25.320660 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]   File "/usr/lib/python2.7/dist-packages/bottle.py", line 1737, in wrapper
[Thu Mar 02 23:57:25.320665 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]     rv = callback(*a, **ka)
[Thu Mar 02 23:57:25.320683 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 771, in get_slash
[Thu Mar 02 23:57:25.320688 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]     return render()
[Thu Mar 02 23:57:25.320691 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 784, in render
[Thu Mar 02 23:57:25.320695 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]     main(**kwargs)
[Thu Mar 02 23:57:25.320699 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 723, in main
[Thu Mar 02 23:57:25.320703 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]     monitor = OpenvpnMgmtInterface(cfg, **kwargs)
[Thu Mar 02 23:57:25.320707 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 170, in __init__
[Thu Mar 02 23:57:25.320711 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]     self.collect_data(vpn)
[Thu Mar 02 23:57:25.320715 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 182, in collect_data
[Thu Mar 02 23:57:25.320719 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]     vpn['sessions'] = self.parse_status(status, self.gi, vpn['semver'])
[Thu Mar 02 23:57:25.320723 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 346, in parse_status
[Thu Mar 02 23:57:25.320727 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]     remote_ip = ip_address(remote)
[Thu Mar 02 23:57:25.320731 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]   File "/usr/lib/python2.7/dist-packages/ipaddr.py", line 78, in IPAddress
[Thu Mar 02 23:57:25.320735 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499]     address)
[Thu Mar 02 23:57:25.320738 2017] [wsgi:error] [pid 9506] [client 192.168.1.53:14499] ValueError: '::ffff:71.230.162.47(1194)' does not appear to be an IPv4 or IPv6 address
[Thu Mar 02 23:57:29.512802 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514] Traceback (most recent call last):
[Thu Mar 02 23:57:29.512856 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]   File "/usr/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
[Thu Mar 02 23:57:29.512861 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]     return route.call(**args)
[Thu Mar 02 23:57:29.512865 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]   File "/usr/lib/python2.7/dist-packages/bottle.py", line 1737, in wrapper
[Thu Mar 02 23:57:29.512869 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]     rv = callback(*a, **ka)
[Thu Mar 02 23:57:29.512873 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 771, in get_slash
[Thu Mar 02 23:57:29.512877 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]     return render()
[Thu Mar 02 23:57:29.512881 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 784, in render
[Thu Mar 02 23:57:29.512885 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]     main(**kwargs)
[Thu Mar 02 23:57:29.512889 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 723, in main
[Thu Mar 02 23:57:29.512893 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]     monitor = OpenvpnMgmtInterface(cfg, **kwargs)
[Thu Mar 02 23:57:29.512897 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 170, in __init__
[Thu Mar 02 23:57:29.512901 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]     self.collect_data(vpn)
[Thu Mar 02 23:57:29.512904 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 182, in collect_data
[Thu Mar 02 23:57:29.512923 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]     vpn['sessions'] = self.parse_status(status, self.gi, vpn['semver'])
[Thu Mar 02 23:57:29.512928 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]   File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 346, in parse_status
[Thu Mar 02 23:57:29.512932 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]     remote_ip = ip_address(remote)
[Thu Mar 02 23:57:29.512935 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]   File "/usr/lib/python2.7/dist-packages/ipaddr.py", line 78, in IPAddress
[Thu Mar 02 23:57:29.512939 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514]     address)
[Thu Mar 02 23:57:29.512943 2017] [wsgi:error] [pid 9509] [client 192.168.1.53:14514] ValueError: '::ffff:71.230.162.47(1194)' does not appear to be an IPv4 or IPv6 address

**Comment by furlongm** [comment]
Looks like it 2.3.10:

From https://www.synology.com/en-us/releaseNote/VPNCenter

"Upgraded OpenVPN to version 2.3.10"

But the output is odd, it appears to include the port in the ip address?

```
'::ffff:71.230.162.47(1194)' does not appear to be an IPv4 or IPv6 address
```

Are you able to run openvpn-monitor.py -d on the command line to debug further?

**Comment by mdthejericho** [comment]
Hi Furlongm, 

I ran that in my first post. Ah! So that version number is just Synology's flavor of OpenVPN. 

I'll attach both the config file and output of openvpn-monitor.py -d 
[openvpn-monitor-d.txt](https://github.com/furlongm/openvpn-monitor/files/840126/openvpn-monitor-d.txt)
[conf.txt](https://github.com/furlongm/openvpn-monitor/files/840128/conf.txt)

**Comment by furlongm** [comment]
Ok, so it looks like the ipv6 address has the port appended in brackets, e.g. ::ffff:71.xx.xx.xx(1194).

Not sure if that's a Synology addition, or if that's how openvpn _used_ to do it. In current versions, the port has been completely removed. See

https://community.openvpn.net/openvpn/ticket/664

for more details. Apart from that it looks like it should work. You could try parsing out the port.

**Comment by mdthejericho** [comment]
Thanks for looking at the logs. Any advice on what I could add to the code to leave out the leading 4 or 6 characters?

**Comment by furlongm** [comment]
Can you try 4127f2f103550bb75d481bee8074043fbe8103b4 and let me know if it works for you?

**Comment by mdthejericho** [comment]
The IPs populated on the Web UI !


Thanks!

**Comment by furlongm** [comment]
Great. I'll close this issue now.
