### ISSUE TITLE
semantic_version does not load ! Completely Hopeless

### ISSUE THREAD

**Issue by aarvee11** [furlongm/openvpn-monitor#43]
Traceback (most recent call last):
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 36, in <module>
    from semantic_version import Version as semver
ImportError: No module named semantic_version
[Wed Apr 26 13:22:07.726903 2017] [cgid:error] [pid 8431:tid 140082247436032] [client 172.31.7.187:54704] End of script output before headers: openvpn-monitor.py

prompt@IT-OpenVPN-Server:/var/www/html/openvpn-monitor# pip install semantic_version
Requirement already satisfied: semantic_version in /usr/local/lib/python2.7/dist-packages
prompt@IT-OpenVPN-Server:/var/www/html/openvpn-monitor# apt-get install python-semantic_version
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-semantic_version
prompt@IT-OpenVPN-Server:/var/www/html/openvpn-monitor# apt-get install python-semantic-version
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-semantic-version
prompt@IT-OpenVPN-Server:/var/www/html/openvpn-monitor# apt-get install python_semantic_version
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python_semantic_version

**Comment by Tarak-Ram** [comment]
Hi there, 
Looks like you are not on Ubuntu 16. For Ubuntu < 16 try to download respective package from http://bitly.com/2pq1NiD.

```
reddy-HP-15-Notebook-PC tmp # **dpkg -i python-semantic-version_2.3.1-1_all.deb** 
Selecting previously unselected package python-semantic-version.
(Reading database ... 229708 files and directories currently installed.)
Preparing to unpack python-semantic-version_2.3.1-1_all.deb ...
Unpacking python-semantic-version (2.3.1-1) ...
Setting up python-semantic-version (2.3.1-1) ...
reddy-HP-15-Notebook-PC tmp # **cat /etc/os-release** 
NAME="Ubuntu"
VERSION="**14.04.5** LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
reddy-HP-15-Notebook-PC tmp # 
```

Thanks.

**Comment by furlongm** [comment]
Solution provided by @Tarak-Ram, thanks!
