### ISSUE TITLE
README install update

### ISSUE THREAD

**Issue by tony-caffe** [furlongm/openvpn-monitor#50]
The install instructions for CentOS 6 are incorrect.

`yum install -y python-GeoIP python-ipaddr python-humanize python-bottle python-semantic_version httpd mod_wsgi git wget`

`python-semantic_version` does not exist in the repo. To install, use pip:

```
yum install python-pip
pip install semantic_version
```

**Comment by furlongm** [comment]
Yeah I was trying to keep the installation instructions as simple as possible. Assumed most people would be on CentOS 7. Maybe I should just state the minimum versions of packages/distros expected?

**Comment by furlongm** [comment]
Targeting Centos7/RHEL7 for future releases, but this issue can serve as documentation for anyone looking for install instructions for Centos6.
