### ISSUE TITLE
Openvpn-monirtor instalaltion issue

### ISSUE THREAD

**Issue by Michealpool** [furlongm/openvpn-monitor#52]
Hi,

I am getting below error while installing it on ubuntu 14.04 . Plz guide for solution.

 pip install openvpn-monitor                                                                                         gunicorn
Downloading/unpacking openvpn-monitor
  Could not find a version that satisfies the requirement openvpn-monitor (from                                                                                         versions: 1.0.0rc19, 1.0.0rc19.linux-x86_64)
Cleaning up...
No distributions matching the version for openvpn-monitor
Storing debug log for failure in /root/.pip/pip.log

**Comment by Michealpool** [comment]
anyone face this???

**Comment by furlongm** [comment]
I've uploaded a new version to pypi. Can you try now and let me know if it works?

**Comment by furlongm** [comment]
New package uploaded, closing.
