### ISSUE TITLE
Bug fix / Enhancement - mgmt state format change in openvpn v2.4.2

### ISSUE THREAD

**Issue by scomoletti** [furlongm/openvpn-monitor#53]
Looks like 2.4.2 changed the output of the state command from 5 fields to 8. Docs at openvpn.net still show the 2.4.1 behavior. Below is output from a few of my test systems.

2.4.13 client
time,state,opt desc,local tun/tap ip,remote ip
1491408625,CONNECTED,SUCCESS,10.0.0.2,172.16.0.1

2.4.13 server:
time,state, opt desc,local tun/tap ip,<empty>
1500864651,CONNECTED,SUCCESS,10.0.0.1,

2.4.2 client:
time,state,opt desc,local tun/tap ipaddr,remote ip,remote port,local outbound ip,local outbound port
1500865657,CONNECTED,SUCCESS,10.0.0.2,172.16.0.1,1194,10.1.1.1,39962

2.4.3 server:
time,state,opt desc,local tun/tap ipaddr,<empty>,<empty>,local listen ip,local listen port
1499703301,CONNECTED,SUCCESS,10.0.0.1,,,172.16.0.1,1194

Really no impact right now as the client vs server logic still works with the parts[4] still being empty on a server.

I may update parse_state to check version, split the line correctly, and add the local port for the tun/tap and the listen ip/port to the page. So I guess we can mark this as an enhancement.

**Comment by furlongm** [comment]
Below is the output I see from 2.4.3. It has the extra fields, but no values.

```
state
1505877121,CONNECTED,SUCCESS,10.0.0.1,,,,
END
version
OpenVPN Version: OpenVPN 2.4.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 21 2017
Management Version: 1
END
```

**Comment by furlongm** [comment]
Closing this issue as there is no impact. Feel free to reopen if that is incorrect.
