### ISSUE TITLE
Getting 404 error on monitoring page after install

### ISSUE THREAD

**Issue by ethanostrow** [furlongm/openvpn-monitor#54]
When I render the monitoring page in my terminal, everything works perfectly but when the URL in the documentation is visited in the browser an error 404 appears. Has anyone had a similar problem?
Attached is server.conf and openvpn-monitor.conf along with the terminal and web page renders:

![useme2](https://user-images.githubusercontent.com/5414435/29759559-b127f42e-8b71-11e7-84e4-88bf0dd4230f.PNG)
![useme3](https://user-images.githubusercontent.com/5414435/29759560-b127f7e4-8b71-11e7-8c35-84caef9a47ff.PNG)
![useme](https://user-images.githubusercontent.com/5414435/29759561-b129fdaa-8b71-11e7-8699-a3c9aec2eada.PNG)
![useme1](https://user-images.githubusercontent.com/5414435/29759562-b13b0082-8b71-11e7-80ff-d956f5d68752.PNG)

**Comment by furlongm** [comment]
I think this is a web server configuration issue, not an openvpn-monitor issue. Closing for now, but feel free to reopen if it's still not working and you have more info.
