### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by davidethebolo** [furlongm/openvpn-monitor#56]
Hi all, 

I have a openvpn running on port 1194 and the management running on 5555 (lsof, nstat, telnet: everything is ok).

Some details:  /etc/openvpn/server.conf contains: **management 127.0.0.1 5555**

openvpn.log contains: **MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:5555**

> lsof -i :5555
**COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
openvpn 14028 nobody    3u  IPv4  31776      0t0  TCP localhost:personal-agent (LISTEN)**

> telnet 127.0.0.1 5555
**Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
>INFO:OpenVPN Management Interface Version 1 -- type 'help' for more info**

but running the container: 

**docker run -d -e OPENVPNMONITOR_DEFAULT_DATETIMEFORMAT="%%d/%%m/%%Y" -e OPENVPNMONITOR_DEFAULT_LATITUDE=10 -e OPENVPNMONITOR_DEFAULT_LONGITUDE=9 -e OPENVPNMONITOR_DEFAULT_MAPS=True -e OPENVPNMONITOR_DEFAULT_SITE='Test' -e OPENVPNMONITOR_SITES_0_ALIAS=UDP -e OPENVPNMONITOR_SITES_0_HOST=127.0.0.1 -e OPENVPNMONITOR_SITES_0_NAME=VPN -e OPENVPNMONITOR_SITES_0_PORT=5555 -p 80:80 ruimarinho/openvpn-monitor**

I can only see: **Could not connect to 127.0.0.1:5555 (Connection refused)**

What I am doing wrong? Can you pls help me?

Thanks!

**Comment by furlongm** [comment]
Please open docker issues here:

https://github.com/ruimarinho/docker-openvpn-monitor/issues

**Comment by PPillau** [comment]
Did you have any success with your error? Because I am encountering the same problem... just don't know what I should put into the SITES_0_HOST variable... nowhere in any docs is that actually explained properly...

**Comment by NetSnipe-20** [comment]
It's frustrating, I don't have any success yet. I have Openvpn 2.7 on
production and it does not have "server.conf" or what so ever file I can
insert "Management 127.0.0.1 5555" I think they are referring to an old
Openvpn version or build. there is a howto guide to export and import
settings but there's no clear guide on how's the format is going to be.

Let me know if you have progress on this one please.

Thanks

**Comment by longGr** [comment]
Do you have ufw running? That was my problem. You have to allow traffic from the docker network to your hosts network:

    ufw allow 172.17.0.2 to 172.17.0.1 port 5555

check the network with 

    ifconfig 

and watch out for docker0 network. This is your host network ip. 

Also bind the management console to 

    management 172.17.0.1 5555

and then for the docker command:

    -e OPENVPNMONITOR_SITES_0_HOST=172.17.0.2
