### ISSUE TITLE
an idea for the map.

### ISSUE THREAD

**Issue by sunadtudk** [furlongm/openvpn-monitor#57]
We got many OpenVPN server around the world. 
We will love to have an option to have multible OpenVPN Server output. 
(NOT as a folder for each server, as we tryed)
Maybe change the map to Google earth or a zoom-scrolling map-location, 
since we got VPNservers and clients all over the world.

**Comment by furlongm** [comment]
This is already implemented?

You can already have multiple VPN servers using new section for each VPN in the config file. The maps already zoom. Using leaflet for maps, but the Google maps code is still there if you want to dig it out. 

Closing this for now, but feel free to re-open if you need more info.
