### ISSUE TITLE
ipv6 error

### ISSUE THREAD

**Issue by jason56783** [furlongm/openvpn-monitor#6]
Hi there, 
i like your monitor and use it quite often. Today I updated it and now i get this error: 
`[Thu Feb 25 19:14:37 2016] [error] [client 10.0.0.200] Traceback (most recent call last):
[Thu Feb 25 19:14:37 2016] [error] [client 10.0.0.200]   File "/var/www_ui/vpn/openvpn-monitor.py", line 29, in <module>
[Thu Feb 25 19:14:37 2016] [error] [client 10.0.0.200]     from humanize import naturalsize
[Thu Feb 25 19:14:37 2016] [error] [client 10.0.0.200] ImportError: No module named humanize
[Thu Feb 25 19:14:37 2016] [error] [client 10.0.0.200] Premature end of script headers: openvpn-monitor.py`

Befor that I had to change the code a little to support IPv6 Addresses. I changed it, so it showed all remote ip addresses as 127.0.0.1. Not a good solution, but it worked so far.Perhaps you find time to fix that.

grettings.

**Comment by furlongm** [comment]
Can you try apt-get install python-humanize ?

**Comment by jason56783** [comment]
ahh, that worked out, thank you.

Now it´s only the IPv6 problem left.
```
File "/openvpn-monitor.py", line 297, in openvpn_parse_status
   session['remote_ip'], session['port'] = tmp[2].split(':')
ValueError: too many values to unpack
```

**Comment by furlongm** [comment]
ipv6 should be working now.

Please pull the latest revision and let me know if there are any issues.

**Comment by jason56783** [comment]
i get the same error
`  Traceback (most recent call last):
    File "/var/www_ui/vpn/openvpn-monitor.py", line 679, in <module>
      main()
    File "/var/www_ui/vpn/openvpn-monitor.py", line 639, in main
      openvpn_collect_data(vpn)
    File "/var/www_ui/vpn/openvpn-monitor.py", line 603, in openvpn_collect_data
      vpn['sessions'] = openvpn_parse_status(status)
    File "/var/www_ui/vpn/openvpn-monitor.py", line 302, in openvpn_parse_status
      remote_ip, port = tmp[2].split(':')
  ValueError: too many values to unpack
  Premature end of script headers: openvpn-monitor.py`

**Comment by furlongm** [comment]
Can you add this line:

debug(tmp[2])

before line 302, and send me the output of python openvpn-monitor.py -d
1>/dev/null

Thanks

**Comment by jason56783** [comment]
this is the output
`::ffff:XX.XXX.XXX.XX`
I XX´t the ipv4 adress... i think this format comes from enabling ipv6 in openvpn

**Comment by jason56783** [comment]
this is complete tmp
`[u'CLIENT_LIST', u'USER1', u'::ffff:XX.XXX.XXX.XX', u'10.0.0.18', u'27699', u'27028', u'Fri Feb 26 15:23:46 2016', u'1456496626']`

**Comment by furlongm** [comment]
Is there a port number after the ipv4 part of the hybrid ipv6 address?

**Comment by jason56783** [comment]
no.... there is no port number. I XX´t only the IP part

**Comment by furlongm** [comment]
Can you check if the latest commit works for you?

ipv4_mapped ipv6 addresses are converted to ipv4 addresses. Otherwise geoip lookups don't work and the ipv6 address doesn't show the ipv6 representation that openvpn gives us (so we don't see the actual ipv4 address). However, ipv6 addresses should be recognised and dealt with correctly now.

**Comment by jason56783** [comment]
okay, half of the page is now loading. Then comes this error:
` Traceback (most recent call last):
   File "/var/www_ui/vpn/openvpn-monitor.py", line 695, in <module>
     main()
   File "/var/www_ui/vpn/openvpn-monitor.py", line 661, in main
     print_vpn(vpn)
   File "/var/www_ui/vpn/openvpn-monitor.py", line 438, in print_vpn
     print_session_table(vpn_mode, vpn_sessions)
   File "/var/www_ui/vpn/openvpn-monitor.py", line 498, in print_session_table
     print_server_session(session)
   File "/var/www_ui/vpn/openvpn-monitor.py", line 470, in print_server_session
     full_location = '{0!s}, {1!s}'.format(city, country)
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 1: ordinal not in range(128)`

I debugged city and country:
` DEBUG:
  D\xfclmen
 DEBUG:
  Germany`

If think this is a umlaut problem(äüö). The city should be Dülmen I think.
Here is a screen of the Page:
![vpn](https://cloud.githubusercontent.com/assets/15936385/13400581/c26e22f6-df08-11e5-9b09-33590a3529d4.jpg)

**Comment by furlongm** [comment]
Ok, so it works on python3 but not python2.

I've added some code to set the default encoding to utf-8 for python2. Can you let me know if that works?

**Comment by jason56783** [comment]
this is the look under python 2.7.3:
![vpn](https://cloud.githubusercontent.com/assets/15936385/13422384/b5334120-df94-11e5-994d-5d68054bcc8f.png)
I also wonder about the clients count. I says 16 clients conncected, but I can see only 14 rows. 

When i change to python 3.4.2 i get this error:
`Premature end of script headers: openvpn-monitor.py`

**Comment by furlongm** [comment]
If you run python openvpn-monitor.py , what is the error?

**Comment by jason56783** [comment]
`user@server: /var/www/vpn# python3 openvpn-monitor.py
Segmentation fault
`

**Comment by furlongm** [comment]
Not sure what the python3 segmentation fault is about.

For the python2 issue, there is in fact missing data. This is due to the fact there there is no port displayed with the ipv6 Real Address. So if someone is connecting twice or more from the same IP address, with the same username, we have no way to distinguish those sessions.

We could in theory use the combination of Remote IP, Local IP and username. However, sometimes Local IP does not exist, so that leaves us with no consistent way to tell them apart.

**Comment by jason56783** [comment]
Doesnt every client get his own virtual IP? This should be an unique address and you can distinguish clients by their virtual ip. No matter of same remote IP´s.

I dont have same Usernames, but same IP´s.

**Comment by furlongm** [comment]
Not every client gets a virtual IP. Sometimes no virtual IP is given out, yet the client is still connected. For example, if IP address exhaustion occurs. Also when the client is first connecting, there is no route and no virtual IP, yet the connection shows up.

I have submitted a bug report and a patch upstream to openvpn:

https://community.openvpn.net/openvpn/ticket/664
