### ISSUE TITLE
How to show the IPv6 address in the web?

### ISSUE THREAD

**Issue by guznoer** [furlongm/openvpn-monitor#60]
Hi Furlong, I already use your tool for managing my OpenVPN for IPv6 tunnel broker in my project and it works great.
Is it possible for me to show the IP version 6 as well when there are clients connection ? As your program now only show the IP version 4 in the client VPN IP column.
To illustrate, I use command in my OpenVPN Management Interface:
_status
OpenVPN CLIENT LIST
Updated,Fri Dec 29 14:01:24 2017
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
android, A.B.C.D:F,335532,1561398,Fri Dec 29 14:00:21 2017 **(note: i change the IPv4 and port address here for security reasons)**
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
**AAAA:BBBB:C:DDDD:EF::1111**,android,A.B.C.D:F,Fri Dec 29 14:01:24 2017 **(note: i change the IPv4 and port address also IPv6 address here for security reasons)**
10.8.0.101,android,A.B.C.D:F,Fri Dec 29 14:01:24 2017  **(note: i change the IPv4 and port address here for security reasons)**
GLOBAL STATS
Max bcast/mcast queue length,0
END_ 
While in your web-based tool the client status shown as below:
![image](https://user-images.githubusercontent.com/34933599/34431812-c641951a-eca4-11e7-9705-cc7c9ca1cd5e.png)

As you can see it only shows the local IPv4 address : 10.8.0.101 while the IPv6 address: AAAA:BBBB:C:DDDD:EF::1111 can't be shown.
Hopefully, You can show me which part of the code that I need to add, to be able to show the IPv6 address part in the web.

Thank you in advance.
_Note: I'm using OpenVPN 2.3.2 for the tunnel server_

**Comment by guznoer** [comment]
Hi furlong, I managed to solve this problem by adding several lines of code in your openvpn-monitor.py file as follow:
In your parse_status static method, below the line "if routes_section" i add the following code:
`remote_str_route = parts[3]
if remote_str_route.count(':') == 1:
       remote_route, port_route = remote_str_route.split(':')
elif '(' in remote_str_route:
       remote_route, port_route = remote_str_route.split('(')
       port_route = port_route[:-1]
else:
       remote_route = remote_str_route
       port_route = None		
for key, session in list(sessions.items()):
       if isinstance(ip_address(local_ip), IPv6Address) \
		and session['remote_ip'] == ip_address(remote_route) \
		and session['port'] == int(port_route):
           sessions[key]['local_ipv6_new'] = ip_address(local_ip)
	   break`
by adding the code above, I add new information about the IPv6 address routing table in sessions[key]['local_ipv6_new']. And to print the new session data, I add the following code in print_session_table_headers static method:
`server_headers = ['Username / Hostname', 'VPN IP', '**VPN IPv6**',
                          'Remote IP', 'Location', 'Bytes In',
                          'Bytes Out', 'Connected Since', 'Last Ping', 'Time Online']`
and also in print_server_session method:
`if session['local_ipv6_new']:
    output('<td>{0!s}</td>'.format(session['local_ipv6_new']))
else:
    output('<td>{0!s}</td>'.format('N/A')`
The end result is like this:
![image](https://user-images.githubusercontent.com/34933599/34813452-a79b1b26-f6dc-11e7-9733-45b8e893963e.png)
I add new column in the blue circle.

**Comment by furlongm** [comment]
Great, if you send a PR, I can merge it.

**Comment by guznoer** [comment]
Ok, I think I've added the PR, please check it :)

**Comment by furlongm** [comment]
Looks like you made the PR against your own fork. Can you PR against my repo?
