### ISSUE TITLE
Only One Connected Client Listed

### ISSUE THREAD

**Issue by canuckbrian** [furlongm/openvpn-monitor#65]
I have 5 clients connected to my OpenVPN server, but your interface is only showing one of the 5.

![openvpn-status](https://user-images.githubusercontent.com/5985280/36277001-6ef35b84-1244-11e8-882d-268d04cae95d.png)

![web-status](https://user-images.githubusercontent.com/5985280/36277304-5d3fa2d4-1245-11e8-9dc8-a05211661685.png)

**Comment by TheAmigo** [comment]
@canuckbrian What version of OpenVPN are you running? (and on what OS?)  I'm running 2.4.3 on CentOS 7 and it shows extra columns in the status.log that your screenshot doesn't include.

**Comment by furlongm** [comment]
Version is 2.3.4 from the image. @canuckbrian can you install 2.4 and see if the issue persists?

**Comment by yoda27mhz** [comment]
The configuration on my server use a bridge interface and the clients get a ip of internal dhcp(not the pool of ips of openvpn). The list of clients, no have the virtual ip. The number of clients its ok, but only see the last of CLIENT_LIST.  I running the 2.4.6.

![image](https://user-images.githubusercontent.com/41153844/42632659-353fed22-85de-11e8-96e4-825b5288d350.png)

**Comment by furlongm** [comment]
@yoda27mhz can you provide debug output as per the README?

**Comment by furlongm** [comment]
Closing due to no responses
