### ISSUE TITLE
Clients who have disconnected appear as connected

### ISSUE THREAD

**Issue by gcleaves** [furlongm/openvpn-monitor#69]
Hello. Thanks for the software, it is very useful. I have noticed some unexpected behaviour in that it takes 1 or 2 minutes for a client to disappear from the monitor after it has disconnected. Is this expected?

Cheers.

**Comment by TheAmigo** [comment]
When using UDP, that's normal.  OpenVPN waits until the client misses a few heartbeats and then assumes it's disconnected.  You can improve this by adding "explicit-exit-notify 1" to the client config file.

It affects OpenVPN, not just openvpn-monitor issue.

**Comment by furlongm** [comment]
Workaround provided by @TheAmigo . Closing.

**Comment by sebastien4** [comment]
Using Tunnelblick, client never disappear from monitor. Works fine with OpenVPN Connect on Android.
Have you ever heard about that issue? Seems related to Tunnelblick..

OpenVPN 2.4.0 (PiVPN).

Cheers.
