### ISSUE TITLE
Ubuntu 14.04

### ISSUE THREAD

**Issue by waikariboy** [furlongm/openvpn-monitor#7]
Traceback (most recent call last):
  File "openvpn-monitor.py", line 31, in <module>
    from humanize import naturalsize
ImportError: No module named humanize

Having issues trying to work out how to install python-humanize, i installed python3-humanize

**Comment by waikariboy** [comment]
got it, i used this site http://neuro.debian.net/install_pkg.html?p=python3-humanize to get me python-humanize

**Comment by furlongm** [comment]
You can also use pip, e.g. pip install humanize (but if you have debian versions, that would probably be best :)
