### ISSUE TITLE
on pfsense?

### ISSUE THREAD

**Issue by somedevreally** [furlongm/openvpn-monitor#77]
Anyway to implement this with pfsense?

**Comment by furlongm** [comment]
I have previously use socat on pfsense and openvpn-monitor on a remote machine running linux.

**Comment by furlongm** [comment]
Solution is to use socat to run on pfsense to expose the listening socket. I don't remember more details than that, sorry!

**Comment by rjzak** [comment]
Use `socat` like this: `socat unix-connect:/var/etc/openvpn/server.sock tcp4-listen:9999,fork` and update the firewall to allow connections to that port, and **only** from the IP running the OpenVPN Monitor. Install with `pkg install socat`.
