### ISSUE TITLE
No flag showing up

### ISSUE THREAD

**Issue by bk86a** [furlongm/openvpn-monitor#78]
Hi,
Can you point me to a workaround or a solution or a way to troubleshoot an issue where no flags are shown next to the location, pls?

tnx,
Mike

**Comment by mrlongshen** [comment]
hi there.
I fix this by change line 673 in openvpn-monitor.py
flag = '/openvpn-monitor/images/flags/{0!s}.png'.format(session['location'].lower())

then you need to run again openvpn-monitor.py in terminal and it will work ! that all 💃

**Comment by furlongm** [comment]
Per the README:

```
Once configured, navigate to http://myipaddress/openvpn-monitor/

Note the trailing slash, the images may not appear without it.

```
