### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by xultz** [furlongm/openvpn-monitor#80]
Hello

I installed openvpn on a Ubuntu 18.04 server, and I installed openvpn-monitor with docker from https://hub.docker.com/r/ruimarinho/openvpn-monitor/ on the same machine.
I configured the openvpn to open the management in the port 5555, and checked it with a telnet to that port that it connects ok, I can send commands, etc. 
When I open the monitor page from another computer, I get the message "Could not connect to 127.0.0.1:5555 (Connection refused)". I checked several times that I can connect via telnet, when I connect via telnet I can see on the opnvpn log messages about that connection, I disconnect the telnet, restart the docker container, and I see nothing on the openvpn log and the web page allways shows me the same message.

What I am doing wrong?
Thank you for any help!!!

**Comment by furlongm** [comment]
Probably best to ask for support on the docker project.
