### ISSUE TITLE
Where to put .htaccess file

### ISSUE THREAD

**Issue by randomnickname1337** [furlongm/openvpn-monitor#81]
Hi my OVPN monitor works like a dream , buy i want to protect it with Username/Password ...

Installed in /srv/openvpn-monitor 

Where should i place .htaccess ?  

Help will be appreciated

**Comment by randomnickname1337** [comment]
apache conf enabled:

WSGIScriptAlias /openvpn-monitor /var/www/html/openvpn-monitor/openvpn-monitor.py

**Comment by TerAnYu** [comment]
/var/www/html/openvpn-monitor/.htaccess

**Comment by furlongm** [comment]
Answer provided by @TerAnYu
