### ISSUE TITLE
Instructions for GeoIP2 with ClearOS7 (so Centos7/EL7)

### ISSUE THREAD

**Issue by NickJH** [furlongm/openvpn-monitor#82]
Many thanks for the update to GeoIP2. I've been working out how to get this going with ClearOS7 (so this should also apply to Centos7 and EL7).

Centos7 and EL7 do not have the latest GeoIP covering GeoIP2 in their normal repos, but I have found them in http://www.city-fan.org/ftp/contrib/yum-repo/, so you should be able to do the following:

> rpm -Uvh http://www.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-2-1.rhel7.noarch.rpm
> yum install GeoIP geoipupdate geoipupdate-cron --enablerepo=city-fan.org
> yum install python2-geoip2

In openvpn-monitor.conf set:
> geoip_data=/usr/share/GeoIP/GeoLite2-City.mmdb

If updating from the old database, you will need to review /etc/GeoIP.conf. Have a look at the /etc/GeoIP.conf.rpmnew file which will probably work by default.

This should replace the installation of python-GeoIP GeoIP-data GeoIP-update

**Comment by furlongm** [comment]
EPEL has geolite2-city and python2-geoip2. We already installed the EPEL repo so I'll add these two packages to the installation instructions.
