### ISSUE TITLE
After reboot:  bash: gunicorn: command not found

### ISSUE THREAD

**Issue by randomnickname1337** [furlongm/openvpn-monitor#83]
Hello, 
Openvpn Server Monitor is working, but after reboot, when i try to start it:

 gunicorn openvpn-monitor -b 0.0.0.0:80

It says:
bash: gunicorn: command not found

I need to repeat procedure:

cd /srv/openvpn-monitor
virtualenv .
. bin/activate
pip install --upgrade pip
pip install openvpn-monitor gunicorn
gunicorn openvpn-monitor -b 0.0.0.0:80

what im doing wrong ? 
THANKS!

**Comment by furlongm** [comment]
You would need to reactivate the virtualenv as per the instructions (or install gunicorn using a package manager rather than via pip in a virtualenv)

**Comment by kokotko1337** [comment]
@furlongm ty installed it with apt
