### ISSUE TITLE
5555 connection refused please help me

### ISSUE THREAD

**Issue by brett005** [furlongm/openvpn-monitor#93]
i use openvpn 2.5.2 from curl -O http://swupdate.openvpn.org/as/openvpn-as-2.5.2-Debian9.amd_64.deb

where i add management port 5555 ?

**Comment by furlongm** [comment]
For the supported open source version at

```
deb http://build.openvpn.net/debian/openvpn/release/2.4 stretch main
```

You add `management 127.0.0.1 5555` to `/etc/openvpn/default-server.conf`
