### ISSUE TITLE
Successful installation for Raspbian and PiVPN

### ISSUE THREAD

**Issue by sebastien4** [furlongm/openvpn-monitor#96]
PiVPN (OpenVPN for RPi): http://www.pivpn.io

Instructions for Apache/Debian are quite ok, just a few points:

1/ I used _geoipupdate2_ from here: https://github.com/maxmind/geoipupdate2.

Commands to install go runtime on Raspbian:
` wget https://storage.googleapis.com/golang/go1.11.4.linux-armv6l.tar.gz`
` sudo tar -C /usr/local -xvf go1.11.4.linux-armv6l.tar.gz`
` cat >> ~/.bashrc << 'EOF'`
` export GOPATH=$HOME/go`
` export PATH=/usr/local/go/bin:$PATH:$GOPATH/bin`
` EOF`
` source ~/.bashrc`

Then
`go get -u github.com/maxmind/geoipupdate2/cmd/geoipupdate`

2/ After launching _geoipupdate_, GeoIP db is located here: _/usr/local/share/GeoIP/GeoLite2-City.mmdb_.
So don't forget to update path in _openvpn-monitor.conf_.

3/ Guess it's a typo but apt package to install is _python-geoip2_, not _python**2**-geoip2_.

Thanks a lot @furlongm !

**Comment by dnorth98** [comment]
Really helpful, thanks @sebastien4 !  Managed to get everything installed and running on a Pi today.  Fantastic project.

**Comment by furlongm** [comment]
I believe the develop branch has fixed this issue. If not, please reopen.
