### ISSUE TITLE
Future compatibility issue -- Python 2.7 End of life approaching

### ISSUE THREAD

**Issue by clarjon1** [furlongm/openvpn-monitor#98]
Hello,

While this project looks super useful, I'm concerned about its viability due to the fact that you have used python2 to build this project.

Python3 has been available for over 10 years, and python2 is slated to be End Of Life as soon as next year -- the end of life was extended in 2016 to give projects time to migrate over. ( reference: https://legacy.python.org/dev/peps/pep-0373/  ) 

Is there a roadmap to update this application to use supported and recommended versions of python?

**Comment by furlongm** [comment]
Both python2 and python3 are supported, and have been for a long time. Please reopen issue if you can pinpoint where this is not the case.

**Comment by clarjon1** [comment]
Lines 59 and 68 of README.md detailing the dependencies have python2 specific dependencies listed -- python2-geoip2
